export const a1WordsUnit5 = [
	{ id: 1, tr: 'Ağustos', uz: 'avgust' },
	{ id: 2, tr: 'ajanda', uz: 'kundalik' },
	{ id: 3, tr: 'akıl', uz: 'aql' },
	{ id: 4, tr: 'anma', uz: 'xotira' },
	{ id: 5, tr: 'aralık', uz: 'dekabr (oy)' },
	{ id: 6, tr: 'ateş', uz: 'olov, otash (isitma)' },
	{ id: 7, tr: 'baklava', uz: 'paxlava (shirinlik)' },
	{ id: 8, tr: 'balayı', uz: 'asal oyi' },
	{ id: 9, tr: 'bayram', uz: 'bayram' },
	{ id: 10, tr: 'bayramlık', uz: 'bayramlik' },
	{ id: 11, tr: 'bereket', uz: 'mo‘l-ko‘llik, barokat' },
	{ id: 12, tr: 'biricik', uz: 'yagona, birgina' },
	{ id: 13, tr: 'birlikte', uz: 'birgalikda' },
	{ id: 14, tr: 'birliktelik', uz: 'birgalikdalik' },
	{ id: 15, tr: 'boya', uz: 'bo‘yoq' },
	{ id: 16, tr: 'bozuk', uz: 'buzuq' },
	{ id: 17, tr: 'buçuk', uz: 'yarim' },
	{ id: 18, tr: 'buket', uz: 'guldasta' },
	{ id: 19, tr: 'cimri', uz: 'ochko‘z, hasis' },
	{ id: 20, tr: 'Cuma', uz: 'juma' },
	{ id: 21, tr: 'Cumartesi', uz: 'shanba' },
	{ id: 22, tr: 'Çarşamba', uz: 'chorshanba' },
	{ id: 23, tr: 'çeşitli', uz: 'xilma-xil, har xil' },
	{ id: 24, tr: 'çeyrek', uz: 'chorak (4/1 qism)' },
	{ id: 25, tr: 'çorba', uz: 'sho‘rva' },
	{ id: 26, tr: 'çoşku', uz: 'jo’shqinlik, hayajon' },
	{ id: 27, tr: 'dakika', uz: 'daqiqa' },
	{ id: 28, tr: 'dilek', uz: 'tilak' },
	{ id: 29, tr: 'dini', uz: 'diniy' },
	{ id: 30, tr: 'dişçi', uz: 'tish shifokori' },
	{ id: 31, tr: 'dolunay', uz: 'to‘lin oy' },
	{ id: 32, tr: 'düğün', uz: 'halqa, arqon tuguni' },
	{ id: 33, tr: 'egemenlik', uz: 'suverenitet' },
	{ id: 34, tr: 'ekim', uz: 'oktyabr (oy)' },
	{ id: 35, tr: 'evlilik', uz: 'turmush qurganlik' },
	{ id: 36, tr: 'eylül', uz: 'sentyabr (oy)' },
	{ id: 37, tr: 'galeri', uz: 'galereya, ko’rgazma' },
	{ id: 38, tr: 'gelecek', uz: 'kelajak' },
	{ id: 39, tr: 'gençlik', uz: 'yoshlik' },
	{ id: 40, tr: 'geveze', uz: 'mahmadona, sergap' },
	{ id: 41, tr: 'gösteri', uz: 'ko‘rsatish, namoyish' },
	{ id: 42, tr: 'harçlık', uz: 'cho‘ntak puli' },
	{ id: 43, tr: 'harf', uz: 'harf' },
	{ id: 44, tr: 'hayvanat bahçesi', uz: 'hayvonot bog‘i' },
	{ id: 45, tr: 'hazırlık', uz: 'tayyorgarlik' },
	{ id: 46, tr: 'haziran', uz: 'iyun (oy)' },
	{ id: 47, tr: 'hece', uz: 'bo‘g‘in' },
	{ id: 48, tr: 'heyecan', uz: 'hayajon' },
	{ id: 49, tr: 'ilginç', uz: 'qiziqarli' },
	{ id: 50, tr: 'ilkbahar', uz: 'bahor' },
	{ id: 51, tr: 'kasım', uz: 'noyabr (oy)' },
	{ id: 52, tr: 'kaza', uz: 'avtahalokat' },
	{ id: 53, tr: 'kış', uz: 'qish' },
	{ id: 54, tr: 'kurum', uz: 'muassasa' },
	{ id: 55, tr: 'kutlama', uz: 'tabrik, nishonlash' },
	{ id: 56, tr: 'kültür', uz: 'madaniyat' },
	{ id: 57, tr: 'marş', uz: 'madhiya' },
	{ id: 58, tr: 'mart', uz: 'mart (oy)' },
	{ id: 59, tr: 'mavi', uz: 'ko‘k' },
	{ id: 60, tr: 'mayıs', uz: 'may (oy)' },
	{ id: 61, tr: 'mevsim', uz: 'fasl' },
	{ id: 62, tr: 'mezuniyet', uz: 'bitirish (maktab, litsey, universitet)' },
	{ id: 63, tr: 'milli', uz: 'milliy' },
	{ id: 64, tr: 'mola', uz: 'tanaffus' },
	{ id: 65, tr: 'mor', uz: 'siyohrang' },
	{ id: 66, tr: 'nice', uz: 'ancha' },
	{ id: 67, tr: 'nikah', uz: 'nikoh' },
	{ id: 68, tr: 'nikah memuru', uz: 'nikoh registratori' },
	{ id: 69, tr: 'nisan', uz: 'aprel (oy)' },
	{ id: 70, tr: 'odun', uz: 'o‘tin' },
	{ id: 71, tr: 'ömür', uz: 'umr' },
	{ id: 72, tr: 'özel', uz: 'o‘ziga xos' },
	{ id: 73, tr: 'palto', uz: 'palto' },
	{ id: 74, tr: 'Pazar', uz: 'yakshanba, bozor' },
	{ id: 75, tr: 'Pazartesi', uz: 'dushanba' },
	{ id: 76, tr: 'Perşembe', uz: 'payshanba' },
	{ id: 77, tr: 'Program', uz: 'dastur, programma' },
	{ id: 78, tr: 'randevu', uz: 'uchrashuv' },
	{ id: 79, tr: 'resmi', uz: 'rasmiy' },
	{ id: 80, tr: 'rezervasyon', uz: 'band qilish' },
	{ id: 81, tr: 'Salı', uz: 'seshanba' },
	{ id: 82, tr: 'saniye', uz: 'soniya' },
	{ id: 83, tr: 'sarı', uz: 'sariq' },
	{ id: 84, tr: 'saygıdeğer', uz: 'hurmatli' },
	{ id: 85, tr: 'sevgili', uz: 'qadrli, sevikli' },
	{ id: 86, tr: 'sonbahar', uz: 'kuz' },
	{ id: 87, tr: 'son kullanma tarihi', uz: 'yaroqlilik muddati' },
	{ id: 88, tr: 'sürpriz', uz: 'syurpriz' },
	{ id: 89, tr: 'şubat', uz: 'fevral (oy)' },
	{ id: 90, tr: 'temmuz', uz: 'iyul (oy)' },
	{ id: 91, tr: 'toplantı', uz: 'majlis, yig‘ilish' },
	{ id: 92, tr: 'ulusal', uz: 'milliy' },
	{ id: 93, tr: 'ücret', uz: 'narx-navo' },
	{ id: 94, tr: 'vakit', uz: 'vaqt' },
	{ id: 95, tr: 'yaz', uz: 'yoz' },
	{ id: 96, tr: 'yeşil', uz: 'yashil' },
	{ id: 97, tr: 'yılbaşı', uz: 'yil boshi' },
	{ id: 98, tr: 'yıldönümü', uz: 'yillik, yil yakuni' },
	{ id: 99, tr: 'yüzük', uz: 'uzuk' },
	{ id: 100, tr: 'zafer', uz: 'zafer' },
	{ id: 101, tr: 'zorluk', uz: 'qiyinchilik' },
	{ id: 102, tr: 'anlamak', uz: 'tushunmoq' },
	{ id: 103, tr: 'asmak', uz: 'osmoq' },
	{ id: 104, tr: 'atlamak', uz: 'sakramoq' },
	{ id: 105, tr: 'atmak', uz: 'otmoq' },
	{ id: 106, tr: 'beklemek', uz: 'kutmoq' },
	{ id: 107, tr: 'benzemek', uz: 'o‘xshamoq' },
	{ id: 108, tr: 'bozulmak', uz: 'buzulmoq' },
	{ id: 109, tr: 'davet etmek', uz: 'taklif qilmoq' },
	{ id: 110, tr: 'değiştirmek', uz: 'o‘zgartirmoq' },
	{ id: 111, tr: 'devam etmek', uz: 'davom etmoq' },
	{ id: 112, tr: 'dilemek', uz: 'tilamoq' },
	{ id: 113, tr: 'doğmak', uz: 'tug‘ilmoq' },
	{ id: 114, tr: 'eğlenmek', uz: 'ko‘ngil ochmoq, yayramoq' },
	{ id: 115, tr: 'el öpmek', uz: 'qo‘l o‘pmoq' },
	{ id: 116, tr: 'evlenmek', uz: 'turmush qurmoq' },
	{ id: 117, tr: 'gecikmek', uz: 'kechikmoq' },
	{ id: 118, tr: 'gösteri yapmak', uz: 'namoyish qilish' },
	{ id: 119, tr: 'götürmek', uz: 'olib ketmoq' },
	{ id: 120, tr: 'ikram etmek', uz: 'taklif qilmoq' },
	{ id: 121, tr: 'heyecanlanmak', uz: 'hayajonlanmoq' },
	{ id: 122, tr: 'kapanmak', uz: 'yopilmoq, o‘z qobig‘iga o‘ranib olmoq' },
	{ id: 123, tr: 'karşılamak', uz: 'kutib olmoq' },
	{ id: 124, tr: 'katılmak', uz: 'qo‘shilmoq, qatnashmoq' },
	{ id: 125, tr: 'kavuşmak', uz: 'uzoq muddatdan so‘ng uchrashmoq' },
	{ id: 126, tr: 'kayak yapmak', uz: 'chang‘i uchmoq' },
	{ id: 127, tr: 'kolonya dökmek', uz: 'adekolon quyish, dezinfeksiya qilish' },
	{ id: 128, tr: 'korumak', uz: 'himoya qilmoq' },
	{ id: 129, tr: 'kutlamak', uz: 'nishonlamoq, tabriklamoq' },
	{ id: 130, tr: 'öpmek', uz: 'o‘pmoq' },
	{ id: 131, tr: 'para toplamak', uz: 'pul yig‘moq' },
	{ id: 132, tr: 'pişman olmak', uz: 'pushaymon bo‘lmoq' },
	{ id: 133, tr: 'pratik yapmak', uz: 'amaliyot o‘tamoq' },
	{ id: 134, tr: 'satın almak', uz: 'sotib olmoq' },
	{ id: 135, tr: 'sofra hazırlamak', uz: 'stol tuzamoq (taom uchun)' },
	{ id: 136, tr: 'sosyal olmak', uz: 'ijtimoiylashmoq' },
	{ id: 137, tr: 'sürmek', uz: 'davom etmoq' },
	{ id: 138, tr: 'araç sürmek', uz: 'mashina haydash' },
	{ id: 139, tr: 'sürünmek', uz: 'sudralmoq' },
	{ id: 140, tr: 'tadı damağında kalmak', uz: 'mazasi tomog‘ida qolmoq' },
	{ id: 141, tr: 'tasarlamak', uz: 'loyihalash, dizayn qilish' },
	{ id: 142, tr: 'toplamak', uz: 'yig‘moq' },
	{ id: 143, tr: 'uğur getirmek', uz: 'omad keltirmoq' },
	{ id: 144, tr: 'üflemek', uz: 'puflamoq' },
	{ id: 145, tr: 'vedalaşmak', uz: 'vidolashmoq' },
	{ id: 146, tr: 'yakmak', uz: 'yoqmoq (olov)' },
	{ id: 147, tr: 'yaşlanmak', uz: 'qarimoq' },
	{ id: 148, tr: 'yenmek', uz: 'yengmoq' },
	{ id: 149, tr: 'yer ayırtmak', uz: 'band qilmoq' },
	{ id: 150, tr: 'yıkamak', uz: 'yuvmoq' },
	{ id: 151, tr: 'yıkmak', uz: 'yo’q qilish, buzmoq' },
	{ id: 152, tr: 'zaman geçirmek', uz: 'vaqt o‘tkazmoq' },
	{ id: 153, tr: 'ziyaret etmek', uz: 'ziyorat qilmoq, tashrif buyurmoq' },
]
