export const a1WordsUnit2 = [
	{ id: 1, tr: 'aç', uz: 'och' },
	{ id: 2, tr: 'açık', uz: 'ochiq' },
	{ id: 3, tr: 'adres', uz: 'manzil (adres)' },
	{ id: 4, tr: 'akşam', uz: 'kechqurun, oqshom' },
	{ id: 5, tr: 'alışveriş', uz: 'savdo-sotiq' },
	{ id: 6, tr: 'alışveriş merkezi', uz: 'savdo-sotiq markazi' },
	{ id: 7, tr: 'alt', uz: 'ost, pastroq' },
	{ id: 8, tr: 'anahtar', uz: 'kalit' },
	{ id: 9, tr: 'artı', uz: 'qo‘shuv +' },
	{ id: 10, tr: 'aşcı', uz: 'oshpaz' },
	{ id: 11, tr: 'avukat', uz: 'advokat' },
	{ id: 12, tr: 'ay', uz: 'oy' },
	{ id: 13, tr: 'banka', uz: 'bank' },
	{ id: 14, tr: 'başarılı', uz: 'muvaffaqiyatli' },
	{ id: 15, tr: 'bekâr', uz: 'turmush qurmagan, bo‘ydoq yoki ajrashgan' },
	{ id: 16, tr: 'bilet', uz: 'bilet, chipta' },
	{ id: 17, tr: 'bina', uz: 'bino' },
	{ id: 18, tr: 'birçok', uz: 'bir qancha' },
	{ id: 19, tr: 'boş', uz: 'bo‘sh' },
	{ id: 20, tr: 'bozuk', uz: 'buzuq' },
	{ id: 21, tr: 'bölüm', uz: 'bo‘lim' },
	{ id: 22, tr: 'bölü', uz: 'bo’lish' },
	{ id: 23, tr: 'bugün', uz: 'bugun' },
	{ id: 24, tr: 'burada', uz: 'bu yerda' },
	{ id: 25, tr: 'bütün', uz: 'butun' },
	{ id: 26, tr: 'büyük', uz: 'katta' },
	{ id: 27, tr: 'cesur', uz: 'jasur' },
	{ id: 28, tr: 'ciddi', uz: 'jiddiy' },
	{ id: 29, tr: 'çalışkan', uz: 'mehnatkash' },
	{ id: 30, tr: 'çarpı', uz: 'ko‘paytiruv *' },
	{ id: 31, tr: 'çirkin', uz: 'xunuk' },
	{ id: 32, tr: 'çöp kutusu', uz: 'chiqindi qutisi' },
	{ id: 33, tr: 'çünkü', uz: 'chunki' },
	{ id: 34, tr: 'dağınık', uz: 'tartibsiz' },
	{ id: 35, tr: 'dar', uz: 'tor' },
	{ id: 36, tr: 'dergi', uz: 'jurnal' },
	{ id: 37, tr: 'dikkatli', uz: 'e’tiborli, diqqatli' },
	{ id: 38, tr: 'dikkatsiz', uz: 'e’tiborsiz, diqqatsiz' },
	{ id: 39, tr: 'doğru', uz: 'to‘g‘ri' },
	{ id: 40, tr: 'doğum tarihi', uz: 'tug‘ilgan sana, oy, yil' },
	{ id: 41, tr: 'doktor', uz: 'shifikor (doktor)' },
	{ id: 42, tr: 'dolu', uz: 'to‘la' },
	{ id: 43, tr: 'domates', uz: 'pomidor' },
	{ id: 44, tr: 'dosya', uz: 'fayl, papka' },
	{ id: 45, tr: 'durak', uz: 'bekat (ostanovka)' },
	{ id: 46, tr: 'duvar', uz: 'devor' },
	{ id: 47, tr: 'düzenli', uz: 'tartibli, muntazam' },
	{ id: 48, tr: 'eczacı', uz: 'dorixonachi' },
	{ id: 49, tr: 'eğlenceli', uz: 'ko‘ngilochar, qiziqarli, hushchaqchaq' },
	{ id: 50, tr: 'eksi', uz: 'ayiruv' },
	{ id: 51, tr: 'eski', uz: 'eski' },
	{ id: 52, tr: 'eşya', uz: 'ashyo, narsa' },
	{ id: 53, tr: 'evli', uz: 'oilali' },
	{ id: 54, tr: 'fakir', uz: 'kambag‘al' },
	{ id: 55, tr: 'fark', uz: 'farq' },
	{ id: 56, tr: 'fırın', uz: 'pech, non sotadigan do‘kon' },
	{ id: 57, tr: 'form', uz: 'shakl' },
	{ id: 58, tr: 'gazete', uz: 'gazeta' },
	{ id: 59, tr: 'genellikle', uz: 'odatda' },
	{ id: 60, tr: 'genç', uz: 'yosh (odam)' },
	{ id: 61, tr: 'geniş', uz: 'keng' },
	{ id: 62, tr: 'güçlü', uz: 'kuchli' },
	{ id: 63, tr: 'güçsüz', uz: 'kuchsiz' },
	{ id: 64, tr: 'gün', uz: 'kun' },
	{ id: 65, tr: 'gündüz', uz: 'kunduz' },
	{ id: 66, tr: 'güvenli', uz: 'ishonchli, xatarsiz' },
	{ id: 67, tr: 'hafta sonu', uz: 'hafta oxiri' },
	{ id: 68, tr: 'hasta', uz: 'kasal' },
	{ id: 69, tr: 'hastane', uz: 'kasalxona' },
	{ id: 70, tr: 'hemşire', uz: 'hamshira' },
	{ id: 71, tr: 'her zaman', uz: 'har doim' },
	{ id: 72, tr: 'hızlı', uz: 'tez' },
	{ id: 73, tr: 'hostes', uz: 'styuardessa' },
	{ id: 74, tr: 'içecek', uz: 'ichimlik' },
	{ id: 75, tr: 'istasyon', uz: 'stansiya' },
	{ id: 76, tr: 'itfaiyeci', uz: 'o‘t o‘chiruvchi' },
	{ id: 77, tr: 'kaç', uz: 'nechta, qancha' },
	{ id: 78, tr: 'kaçıncı', uz: 'nechanchi' },
	{ id: 79, tr: 'kat', uz: 'qavat' },
	{ id: 80, tr: 'kırmızı', uz: 'qizil' },
	{ id: 81, tr: 'kantin', uz: 'oshxona (maktabda)' },
	{ id: 82, tr: 'kapalı', uz: 'yopiq' },
	{ id: 83, tr: 'kardeş', uz: 'qarindosh, jigar' },
	{ id: 84, tr: 'kasap', uz: 'qassob' },
	{ id: 85, tr: 'kasiyer', uz: 'kassir, hisobchi' },
	{ id: 86, tr: 'kırmızı', uz: 'qizil' },
	{ id: 87, tr: 'kısa', uz: 'qisqa' },
	{ id: 88, tr: 'kıskanç', uz: 'rashkchi, qizg‘anchiq' },
	{ id: 89, tr: 'kibar', uz: 'xushmuomala' },
	{ id: 90, tr: 'kilo', uz: 'kilogramm' },
	{ id: 91, tr: 'kirli', uz: 'kir' },
	{ id: 92, tr: 'kitaplık', uz: 'kitob javoni' },
	{ id: 93, tr: 'kolay', uz: 'oson' },
	{ id: 94, tr: 'komik', uz: 'kulguli, hazilkash' },
	{ id: 95, tr: 'konuşkan', uz: 'ko‘p gapiruvchi, suhbatga kirishimli' },
	{ id: 96, tr: 'koridor', uz: 'yo‘lak, koridor' },
	{ id: 97, tr: 'kötü', uz: 'yomon' },
	{ id: 98, tr: 'kuaför', uz: 'sartarosh (ayollar)' },
	{ id: 99, tr: 'kuyumcu', uz: 'zargar' },
	{ id: 100, tr: 'küçük', uz: 'kichkina' },
	{ id: 101, tr: 'lamba', uz: 'lampa' },
	{ id: 102, tr: 'lig', uz: 'liga (sportda)' },
	{ id: 103, tr: 'liste', uz: 'ro‘yxat' },
	{ id: 104, tr: 'mahalle', uz: 'mahalla' },
	{ id: 105, tr: 'manav', uz: 'sabzavot do‘koni' },
	{ id: 106, tr: 'market', uz: 'market, do‘kon' },
	{ id: 107, tr: 'mutfak', uz: 'oshxona (uydagi)' },
	{ id: 108, tr: 'mutlu', uz: 'baxtli, xursand' },
	{ id: 109, tr: 'mutsuz', uz: 'baxtsiz' },
	{ id: 110, tr: 'nerede', uz: 'qayerda' },
	{ id: 111, tr: 'nesne', uz: 'ob‘ekt' },
	{ id: 112, tr: 'niçin', uz: 'nima uchun' },
	{ id: 113, tr: 'ocak', uz: 'yanvar' },
	{ id: 114, tr: 'ofis', uz: 'ofis' },
	{ id: 115, tr: 'olimpiyat', uz: 'olimpiada' },
	{ id: 116, tr: 'orada', uz: 'u yerda' },
	{ id: 117, tr: 'öğleden sonra', uz: 'tushdan(obeddan) keyin' },
	{ id: 118, tr: 'öğretmen', uz: 'o‘qituvchi' },
	{ id: 119, tr: 'önemli', uz: 'muhim' },
	{ id: 120, tr: 'önemsiz', uz: 'nomuhim' },
	{ id: 121, tr: 'pahalı', uz: 'qimmat' },
	{ id: 122, tr: 'pastane', uz: 'qandolatxona' },
	{ id: 123, tr: 'pembe', uz: 'pushti' },
	{ id: 124, tr: 'polis', uz: 'militsiya' },
	{ id: 125, tr: 'postane', uz: 'pochtaxona' },
	{ id: 126, tr: 'projektör', uz: 'proyektor' },
	{ id: 127, tr: 'psikolog', uz: 'psixolog' },
	{ id: 128, tr: 'sayı', uz: 'son' },
	{ id: 129, tr: 'sabah', uz: 'ertalab, tong' },
	{ id: 130, tr: 'sağlam', uz: 'soz, sog‘lom' },
	{ id: 131, tr: 'sehpa', uz: 'gazeta stoli (qahva stoli)' },
	{ id: 132, tr: 'sekreter', uz: 'sekretar' },
	{ id: 133, tr: 'semt', uz: 'guzar, massiv' },
	{ id: 134, tr: 'sessiz', uz: 'sokin, kamgap' },
	{ id: 135, tr: 'sıcak', uz: 'issiq' },
	{ id: 136, tr: 'sıfat', uz: 'sifat' },
	{ id: 137, tr: 'sinirli', uz: 'asabiy, jahldor' },
	{ id: 138, tr: 'soğuk', uz: 'sovuq' },
	{ id: 139, tr: 'sokak', uz: 'ko‘cha' },
	{ id: 140, tr: 'sosyal', uz: 'sotsial, ijtimoiy kirishimli' },
	{ id: 141, tr: 'şehir', uz: 'shahar' },
	{ id: 142, tr: 'şimdi', uz: 'hozir' },
	{ id: 143, tr: 'şimdilik', uz: 'hozircha' },
	{ id: 144, tr: 'şişman', uz: 'semiz' },
	{ id: 145, tr: 'tabak', uz: 'idish-tovoq' },
	{ id: 146, tr: 'tamirci', uz: 'ta‘mirlovchi' },
	{ id: 147, tr: 'tarih', uz: 'tarix, sana' },
	{ id: 148, tr: 'tatil', uz: 'ta’til, bayram (kanikul)' },
	{ id: 149, tr: 'tehlikeli', uz: 'tahlikali, xatarli' },
	{ id: 150, tr: 'tembel', uz: 'yalqov, ishyoqmas, tambal' },
	{ id: 151, tr: 'temiz', uz: 'toza' },
	{ id: 152, tr: 'temizlik görevlisi', uz: 'farrosh, tozalik xodimi' },
	{ id: 153, tr: 'tezgahtar', uz: 'sotuvchi' },
	{ id: 154, tr: 'tuzlu', uz: 'tuzli, sho‘r' },
	{ id: 155, tr: 'ucuz', uz: 'arzon' },
	{ id: 156, tr: 'uzak', uz: 'uzoq' },
	{ id: 157, tr: 'uzun', uz: 'uzun' },
	{ id: 158, tr: 'üst', uz: 'ust, tepa' },
	{ id: 159, tr: 'var', uz: 'bor' },
	{ id: 160, tr: 'veteriner', uz: 'veterinar' },
	{ id: 161, tr: 'yakın', uz: 'yaqin' },
	{ id: 162, tr: 'yanlış', uz: 'xato, yanglish' },
	{ id: 163, tr: 'yarışma', uz: 'musobaqa' },
	{ id: 164, tr: 'yastık', uz: 'yostiq' },
	{ id: 165, tr: 'yaş', uz: 'yosh' },
	{ id: 166, tr: 'yaşlı', uz: 'yoshi katta, qari' },
	{ id: 167, tr: 'yavaş', uz: 'sekin, bosiq' },
	{ id: 168, tr: 'yazı tahtası', uz: 'doska, yozuv taxtasi' },
	{ id: 169, tr: 'yeni', uz: 'yangi' },
	{ id: 170, tr: 'yer', uz: 'joy' },
	{ id: 171, tr: 'yıl', uz: 'yil' },
	{ id: 172, tr: 'yiyecek', uz: 'yegulik' },
	{ id: 173, tr: 'yoğun', uz: 'band' },
	{ id: 174, tr: 'yok', uz: 'yo‘q' },
	{ id: 175, tr: 'yorgun', uz: 'horg‘in, charchagan' },
	{ id: 176, tr: 'yorucu', uz: 'charchatuvchi' },
	{ id: 177, tr: 'yumuşak', uz: 'yumshoq' },
	{ id: 178, tr: 'zamir', uz: 'olmosh (so‘z turkumi)' },
	{ id: 179, tr: 'zayıf', uz: 'ozg‘in' },
	{ id: 180, tr: 'zengin', uz: 'boy' },
	{ id: 181, tr: 'zor', uz: 'qiyin' },
	{ id: 182, tr: 'aramak', uz: 'qidirmoq, qo‘ng‘iroq qilmoq' },
]
