export const a1WordsUnit4 = [
	{ id: 1, tr: 'abla', uz: 'opa' },
	{ id: 2, tr: 'ağabey', uz: 'aka' },
	{ id: 3, tr: 'ağız', uz: 'og‘iz' },
	{ id: 4, tr: 'aile', uz: 'oila' },
	{ id: 5, tr: 'amca', uz: 'amaki' },
	{ id: 6, tr: 'anadil', uz: 'ona tili' },
	{ id: 7, tr: 'anahtar', uz: 'kalit' },
	{ id: 8, tr: 'anaokulu', uz: 'bolalar bog‘chasi' },
	{ id: 9, tr: 'anneanne', uz: 'buvi (ona taraf)' },
	{ id: 10, tr: 'Arapça', uz: 'arabcha' },
	{ id: 11, tr: 'Arnavut', uz: 'Albanya' },
	{ id: 12, tr: 'Arnavutça', uz: 'albancha' },
	{ id: 13, tr: 'babaanne', uz: 'buvi (ota taraf)' },
	{ id: 14, tr: 'boyun', uz: 'bo‘yin' },
	{ id: 15, tr: 'burun', uz: 'burun' },
	{ id: 16, tr: 'çift', uz: 'juft' },
	{ id: 17, tr: 'dayı', uz: 'tog‘a' },
	{ id: 18, tr: 'dede', uz: 'buva' },
	{ id: 19, tr: 'diş', uz: 'tish' },
	{ id: 20, tr: 'eğlenceli', uz: 'qiziqarli' },
	{ id: 21, tr: 'enfes', uz: 'mazali' },
	{ id: 22, tr: 'erkek kardeş', uz: 'uka' },
	{ id: 23, tr: 'e-posta', uz: 'elektron pochta' },
	{ id: 24, tr: 'fikir', uz: 'fikr' },
	{ id: 25, tr: 'hala', uz: 'amma' },
	{ id: 26, tr: 'havuz', uz: 'basseyn' },
	{ id: 27, tr: 'hobi', uz: 'hobbi' },
	{ id: 28, tr: 'ilkokul', uz: 'boshlang‘ich ta’lim' },
	{ id: 29, tr: 'İnglizce', uz: 'inglizcha' },
	{ id: 30, tr: 'karı', uz: 'xotin' },
	{ id: 31, tr: 'Kazakça', uz: 'qozoqcha' },
	{ id: 32, tr: 'Kazakistan', uz: 'Qozog‘iston' },
	{ id: 33, tr: 'kız kardeş', uz: 'singil' },
	{ id: 34, tr: 'koca', uz: 'er' },
	{ id: 35, tr: 'kol', uz: 'qo‘l' },
	{ id: 36, tr: 'lise', uz: 'litsey' },
	{ id: 37, tr: 'manto', uz: 'plash' },
	{ id: 38, tr: 'mektup', uz: 'maktub, xat' },
	{ id: 39, tr: 'Mısırlı', uz: 'misrlik' },
	{ id: 40, tr: 'omuz', uz: 'yelka' },
	{ id: 41, tr: 'ortaokul', uz: 'o‘rta ta’lim' },
	{ id: 42, tr: 'profil', uz: 'profil' },
	{ id: 43, tr: 'Rus', uz: 'rus' },
	{ id: 44, tr: 'Rusça', uz: 'ruscha' },
	{ id: 45, tr: 'satranç', uz: 'shaxmat' },
	{ id: 46, tr: 'Sosyal medya', uz: 'ijtimoiy tarmoq' },
	{ id: 47, tr: 'şirket', uz: 'shirkat' },
	{ id: 48, tr: 'teneffüs', uz: 'tanaffus' },
	{ id: 49, tr: 'teyze', uz: 'xola' },
	{ id: 50, tr: 'üniversite', uz: 'universitet' },
	{ id: 51, tr: 'ütü', uz: 'dazmol' },
	{ id: 52, tr: 'yabancı dil', uz: 'chet tili' },
	{ id: 53, tr: 'yaramaz', uz: 'quloq solmas, to‘polonchi' },
	{
		id: 54,
		tr: 'yurt',
		uz: 'yotoqxona (talabalar turar joyiga nisbatan), yurt',
	},
	{ id: 55, tr: 'zevkli', uz: 'zavqli' },
	{ id: 56, tr: 'almak', uz: 'olmoq' },
	{ id: 57, tr: 'anlatmak', uz: 'tushuntirmoq' },
	{ id: 58, tr: 'dans etmek', uz: 'raqsga tushmoq' },
	{ id: 59, tr: 'çalmak', uz: 'o‘g‘irlamoq' },
	{ id: 60, tr: 'kapı çalmak', uz: 'eshik taqillatmoq' },
	{ id: 61, tr: 'hissetmek', uz: 'his qilmoq' },
	{ id: 62, tr: 'yazmak', uz: 'yozmoq' },
	{ id: 63, tr: 'golf oynamak', uz: 'golf o‘ynamoq' },
	{ id: 64, tr: 'göndermek', uz: 'jo‘natmoq' },
	{ id: 65, tr: 'oynamak', uz: 'o‘ynamoq' },
	{ id: 66, tr: 'öğretmek', uz: 'o‘rgatmoq' },
	{ id: 67, tr: 'kalmak', uz: 'qolmoq' },
	{ id: 68, tr: 'kalakalmak', uz: 'hayron bo’lmoq' },
	{ id: 69, tr: 'plan yapmak', uz: 'reja qilmoq' },
	{ id: 70, tr: 'pratik yapmak', uz: 'amaliyot o‘tamoq' },
	{ id: 71, tr: 'selam söylemek', uz: 'salom aytmoq' },
	{ id: 72, tr: 'telefon etmek', uz: 'telefon qilmoq' },
]