export const a1WordsUnit6 = [
	{ id: 1, tr: 'ağrı kesici', uz: 'og‘riq qoldiruvchi' },
	{ id: 2, tr: 'akciğer', uz: 'o‘pka' },
	{ id: 3, tr: 'akıllı', uz: 'aqlli' },
	{ id: 4, tr: 'akraba', uz: 'qarindosh' },
	{ id: 5, tr: 'alan', uz: 'maydon' },
	{ id: 6, tr: 'alın', uz: 'peshona' },
	{ id: 7, tr: 'alt', uz: 'ost, tag' },
	{ id: 8, tr: 'arka', uz: 'orqa' },
	{ id: 9, tr: 'aşağı', uz: 'pasti' },
	{ id: 10, tr: 'ateş düşürücü', uz: 'isitma tushuruvchi' },
	{ id: 11, tr: 'belirti', uz: 'alomat (semptom)' },
	{ id: 12, tr: 'boyun', uz: 'bo‘yin' },
	{ id: 13, tr: 'burun', uz: 'burun' },
	{ id: 14, tr: 'cadde', uz: 'ko‘cha (shohko‘cha)' },
	{ id: 15, tr: 'cesur', uz: 'jasur' },
	{ id: 16, tr: 'ciddi', uz: 'jiddiy' },
	{ id: 17, tr: 'cimri', uz: 'hasis, ochko‘z' },
	{ id: 18, tr: 'cömert', uz: 'saxiy' },
	{ id: 19, tr: 'çene', uz: 'chakak' },
	{ id: 20, tr: 'çevre', uz: 'atrof' },
	{ id: 21, tr: 'çiftçi', uz: 'dehqon' },
	{ id: 22, tr: 'dergi', uz: 'jurnal' },
	{ id: 23, tr: 'dış', uz: 'tashqari' },
	{ id: 24, tr: 'eksik', uz: 'kam' },
	{ id: 25, tr: 'emekli', uz: 'nafaqaxo‘r' },
	{ id: 26, tr: 'enişte', uz: 'pochcha' },
	{ id: 27, tr: 'ev hanımı', uz: 'uy bekasi' },
	{ id: 28, tr: 'göl', uz: 'ko‘l' },
	{ id: 29, tr: 'grip', uz: 'gripp' },
	{ id: 30, tr: 'güler yüzlü', uz: 'kular yuzli, ochiq chehrali' },
	{ id: 31, tr: 'gürültü', uz: 'shovqin-suron' },
	{ id: 32, tr: 'halsiz', uz: 'holsiz' },
	{ id: 33, tr: 'heykel', uz: 'haykal' },
	{ id: 34, tr: 'iç', uz: 'ich' },
	{
		id: 35,
		tr: 'iskele',
		uz: 'tayanch (qayiq, poroxod kabilarning qirg‘oqda ushlab turilishi uchun)',
	},
	{ id: 36, tr: 'iskelet', uz: 'skelet' },
	{ id: 37, tr: 'karın', uz: 'qorin' },
	{ id: 38, tr: 'karşı', uz: 'qarshi' },
	{ id: 39, tr: 'kaş', uz: 'qosh' },
	{ id: 40, tr: 'kırık', uz: 'buzulgan' },
	{ id: 41, tr: 'kız', uz: 'qiz' },
	{ id: 42, tr: 'kibar', uz: 'xushmuomala' },
	{ id: 43, tr: 'klarnet', uz: 'puflama soz' },
	{ id: 44, tr: 'köprü', uz: 'ko‘prik' },
	{ id: 45, tr: 'köşe', uz: 'burchak' },
	{ id: 46, tr: 'kulak', uz: 'quloq' },
	{ id: 47, tr: 'kuzen', uz: 'amakivachcha' },
	{ id: 48, tr: 'kütüphane', uz: 'kutubxona' },
	{ id: 49, tr: 'lezzetli', uz: 'lazzatli' },
	{ id: 50, tr: 'mahalle', uz: 'mahalla' },
	{ id: 51, tr: 'manzara', uz: 'manzara' },
	{ id: 52, tr: 'marka', uz: 'marka' },
	{ id: 53, tr: 'mercimek çorbası', uz: 'yasmiq sho‘rva (chichivichniy sup)' },
	{ id: 54, tr: 'meydan', uz: 'maydon' },
	{ id: 55, tr: 'mümkün', uz: 'mumkin' },
	{ id: 56, tr: 'nehir', uz: 'daryo' },
	{ id: 57, tr: 'neşeli', uz: 'quvnoq' },
	{ id: 58, tr: 'oğul', uz: 'o‘g‘il' },
	{ id: 59, tr: 'omuz', uz: 'yelka' },
	{ id: 60, tr: 'orta', uz: 'o‘rta' },
	{ id: 61, tr: 'otantik', uz: 'haqiqiy' },
	{ id: 62, tr: 'ön', uz: 'old taraf, yuza' },
	{ id: 63, tr: 'parmak', uz: 'barmoq' },
	{ id: 64, tr: 'patlıcan', uz: 'baqlajon' },
	{ id: 65, tr: 'plan', uz: 'plan, reja' },
	{ id: 66, tr: 'rapor', uz: 'hisobot, xulosa (bir ishning xulosasi)' },
	{
		id: 67,
		tr: 'reçete',
		uz: 'doktorlar dori va dozalarini yozib beruvchi qog‘oz',
	},
	{ id: 68, tr: 'renk', uz: 'rang' },
	{ id: 69, tr: 'sağ', uz: 'sog‘, o’ng' },
	{ id: 70, tr: 'sakin', uz: 'sokin, tinch' },
	{ id: 71, tr: 'salıncak', uz: 'arg‘imchoq (asosan arqondan yasaladi)' },
	{ id: 72, tr: 'sebze', uz: 'sabzavotlar' },
	{ id: 73, tr: 'sinirli', uz: 'jahli chiqqan' },
	{ id: 74, tr: 'sınırlı', uz: 'cheklangan' },
	{ id: 75, tr: 'soğuk algınlığı', uz: 'shamollash' },
	{ id: 76, tr: 'sol', uz: 'chap' },
	{ id: 77, tr: 'sözlük', uz: 'lug‘at' },
	{ id: 78, tr: 'şeker', uz: 'shakar' },
	{ id: 79, tr: 'şikâyet', uz: 'shikoyat' },
	{ id: 80, tr: 'şurup', uz: 'sirop' },
	{ id: 81, tr: 'tahmin', uz: 'taxmin' },
	{ id: 82, tr: 'tarihî', uz: 'tarixiy' },
	{ id: 83, tr: 'ten', uz: 'tana' },
	{ id: 84, tr: 'terzi', uz: 'tikuvchi' },
	{ id: 85, tr: 'üst', uz: 'ustki' },
	{ id: 86, tr: 'vücut', uz: 'vujud, tana' },
	{ id: 87, tr: 'yaklaşık', uz: 'taxminan' },
	{ id: 88, tr: 'yanak', uz: 'yanoq' },
	{ id: 89, tr: 'yaramaz', uz: 'quloqsiz, to‘polonchi' },
	{ id: 90, tr: 'yenge', uz: 'yanga, kelinoyi' },
	{ id: 91, tr: 'yukarı', uz: 'yuqori' },
	{ id: 92, tr: 'yüksek lisans', uz: 'magistratura' },
	{ id: 93, tr: 'yüz', uz: 'yuz' },
	{ id: 94, tr: 'ağrımak', uz: 'og‘rimoq' },
	{ id: 95, tr: 'anlaşmak', uz: 'kelishmoq' },
	{ id: 96, tr: 'bayılmak', uz: 'hushidan ketmoq' },
	{ id: 97, tr: 'beğenmek', uz: 'yoqtirmoq' },
	{ id: 98, tr: 'danışmak', uz: 'maslahatlashmoq' },
	{ id: 99, tr: 'değiştirmek', uz: 'almashtirmoq, o‘zgartirmoq' },
	{ id: 100, tr: 'görüşmek', uz: 'ko‘rishmoq' },
	{ id: 101, tr: 'hissetmek', uz: 'his qilmoq' },
	{ id: 102, tr: 'iğne olmak', uz: 'ukol olmoq' },
	{ id: 103, tr: 'ilgilenmek', uz: 'qiziqmoq' },
	{ id: 104, tr: 'inanmak', uz: 'ishonmoq' },
	{ id: 105, tr: 'kaşınmak', uz: 'qashinmoq, qichinmoq' },
	{ id: 106, tr: 'katılmak', uz: 'qatnashmoq, ishtirok etmoq' },
	{ id: 107, tr: 'kızarmak', uz: 'qizarmoq' },
	{ id: 108, tr: 'midesi bulanmak', uz: 'oshqozoni og‘rimoq' },
	{ id: 109, tr: 'sallanmak', uz: 'chayqalmoq' },
	{ id: 110, tr: 'tahlil yaptırmak', uz: 'tahlil qildirmoq (tashxis)' },
	{ id: 111, tr: 'tanımak', uz: 'tanimoq' },
	{ id: 112, tr: 'tansiyon ölçtürmek', uz: 'qon bosimini o‘lchatmoq' },
	{ id: 113, tr: 'tartılmak', uz: 'o’lchanmoq' },
	{ id: 114, tr: 'tedavi olmak', uz: 'davolanmoq' },
	{ id: 115, tr: 'öksürmek', uz: 'yo‘talmoq' },
	{ id: 116, tr: 'vakit geçermek', uz: 'vaqt o‘tkazmoq' },
]
