export const a1WordsUnit3 = [
	{ id: 1, tr: 'anne', uz: 'ona' },
	{ id: 2, tr: 'aynı', uz: 'bir xil' },
	{ id: 3, tr: 'bale', uz: 'balet (raqs turi)' },
	{ id: 4, tr: 'bavul', uz: 'jamadon' },
	{ id: 5, tr: 'beraber', uz: 'birga, barobar' },
	{ id: 6, tr: 'bilet', uz: 'chipta, bilet' },
	{ id: 7, tr: 'bilgisayar oyunu', uz: 'kompyuter o‘yini' },
	{ id: 8, tr: 'borç', uz: 'qarz' },
	{ id: 9, tr: 'boş zaman', uz: 'bo‘sh vaqt' },
	{ id: 10, tr: 'büfe', uz: 'bufet' },
	{ id: 11, tr: 'dans', uz: 'raqs' },
	{ id: 12, tr: 'değişik', uz: 'boshqacha, o’zgacha' },
	{ id: 13, tr: 'dışarı', uz: 'tashqari' },
	{ id: 14, tr: 'dizi', uz: 'serial' },
	{ id: 15, tr: 'ekonomi', uz: 'ekonomiya, iqtisod' },
	{ id: 16, tr: 'erken', uz: 'erta' },
	{ id: 17, tr: 'eski', uz: 'eski' },
	{ id: 18, tr: 'eş', uz: 'turmush o‘rtoq, hamroh' },
	{ id: 19, tr: 'ev hanımı', uz: 'uy bekasi' },
	{ id: 20, tr: 'fabrika', uz: 'fabrika' },
	{ id: 21, tr: 'farklı', uz: 'farqli' },
	{ id: 22, tr: 'fikir', uz: 'fikr' },
	{ id: 23, tr: 'film', uz: 'kino, film' },
	{ id: 24, tr: 'futbol', uz: 'futbol' },
	{ id: 25, tr: 'futbol maçı', uz: 'futbol uchrashuvi (mach)' },
	{ id: 26, tr: 'geç', uz: 'kech' },
	{ id: 27, tr: 'gezi', uz: 'sayr, sayohat' },
	{ id: 28, tr: 'gitar', uz: 'gitara' },
	{ id: 29, tr: 'hava', uz: 'havo' },
	{ id: 30, tr: 'gösteri', uz: 'ko‘rsatuv' },
	{ id: 31, tr: 'hafta içi', uz: 'begim kunlari (dushanba-juma)' },
	{ id: 32, tr: 'hayat', uz: 'hayot' },
	{ id: 33, tr: 'hazır', uz: 'tayyor' },
	{ id: 34, tr: 'hediye', uz: 'sovg‘a, hadiya' },
	{ id: 35, tr: 'her gün/hafta/yaz', uz: 'har kun/hafta/yoz' },
	{ id: 36, tr: 'heyecanlı', uz: 'hayajonli' },
	{ id: 37, tr: 'hiçbir zaman', uz: 'hech qachon' },
	{ id: 38, tr: 'hukuk', uz: 'huquq' },
	{ id: 39, tr: 'içeri', uz: 'ichkari' },
	{ id: 40, tr: 'iş yeri', uz: 'ish joyi' },
	{ id: 41, tr: 'iş adamı', uz: 'tadbirkor, biznesmen' },
	{ id: 42, tr: 'işçi', uz: 'ishchi' },
	{ id: 43, tr: 'kampus', uz: 'universitet shaharchasi' },
	{ id: 44, tr: 'kanepe', uz: 'divan' },
	{ id: 45, tr: 'kebap', uz: 'kabob' },
	{ id: 46, tr: 'kızgın', uz: 'jahldor' },
	{ id: 47, tr: 'konser', uz: 'konsert' },
	{ id: 48, tr: 'kuaför', uz: 'sartarosh (ayol)' },
	{ id: 49, tr: 'kulüp', uz: 'klub' },
	{ id: 50, tr: 'litre', uz: 'litr' },
	{ id: 51, tr: 'maç', uz: 'o`yin' },
	{ id: 52, tr: 'mağaza', uz: 'do‘kon' },
	{ id: 53, tr: 'manikür', uz: 'manyuker' },
	{ id: 54, tr: 'market', uz: 'do‘kon, bozorcha' },
	{ id: 55, tr: 'memur', uz: 'xodim' },
	{ id: 56, tr: 'mp3 çalar', uz: 'mp3 pleer' },
	{ id: 57, tr: 'müsait', uz: 'bo‘sh (vaqtga nisbatan)' },
	{ id: 58, tr: 'müşteri', uz: 'mijoz, xaridor' },
	{ id: 59, tr: 'müze', uz: 'muzey' },
	{ id: 60, tr: 'normal', uz: 'o‘rtacha, me’yorida' },
	{ id: 61, tr: 'opera', uz: 'opera (san‘at turi)' },
	{ id: 62, tr: 'öğlen', uz: 'tush payti' },
	{ id: 63, tr: 'öğrenci işleri', uz: 'o‘quvchi ishlari' },
	{ id: 64, tr: 'pijama', uz: 'tungi kiyim' },
	{ id: 65, tr: 'restoran', uz: 'restoran' },
	{
		id: 66,
		tr: 'resepsiyonist',
		uz: 'qabulxonada ishlovchi xodim (retseption)',
	},
	{ id: 67, tr: 'rezervasyon', uz: 'band qilish' },
	{ id: 68, tr: 'röportaj', uz: 'reportaj' },
	{ id: 69, tr: 'sağlıklı', uz: 'sog‘lom' },
	{ id: 70, tr: 'seans', uz: 'seans, sessiya' },
	{ id: 71, tr: 'sergi', uz: 'ko‘rgazma' },
	{ id: 72, tr: 'sinema', uz: 'kino' },
	{ id: 73, tr: 'site', uz: 'sayt' },
	{ id: 74, tr: 'şarkı', uz: 'qo‘shiq, ashula' },
	{ id: 75, tr: 'şimdi', uz: 'hozir' },
	{ id: 76, tr: 'şiir', uz: 'she’r' },
	{ id: 77, tr: 'terlik', uz: 'uyda kiyiladigan oyoq kiyim, shippak' },
	{ id: 78, tr: 'tiyatro', uz: 'teatr' },
	{ id: 79, tr: 'tur', uz: 'tur (sayohatga oid)' },
	{ id: 80, tr: 'tür', uz: 'tur, nav, xil' },
	{ id: 81, tr: 'uygun', uz: 'mos' },
	{ id: 82, tr: 'vapur', uz: 'poroxod' },
	{ id: 83, tr: 'yalan', uz: 'yolg‘on' },
	{ id: 84, tr: 'yanlış', uz: 'yanglish, xato' },
	{ id: 85, tr: 'yarın', uz: 'ertaga' },
	{ id: 86, tr: 'yazar', uz: 'yozuvchi' },
	{ id: 87, tr: 'yemekhane', uz: 'yemakxona' },
	{ id: 88, tr: 'yeni', uz: 'yangi' },
	{ id: 89, tr: 'yolcu', uz: 'yo‘lovchi' },
	{ id: 90, tr: 'yorum', uz: 'izoh, sharh' },
	{ id: 91, tr: 'yurt', uz: 'talabalar yotoqxonasi, yurt' },
	{ id: 92, tr: 'zaman', uz: 'vaqt, zamon' },
	{ id: 93, tr: 'açmak', uz: 'ochmoq' },
	{ id: 94, tr: 'anlamak', uz: 'tushunmoq' },
	{ id: 95, tr: 'bakmak', uz: 'qaramoq' },
	{ id: 96, tr: 'banyo yapmak', uz: 'vanna qabul qilmoq' },
	{ id: 97, tr: 'başlamak', uz: 'boshlamoq' },
	{
		id: 98,
		tr: 'bayılmak',
		uz: 'haddan ortiq yaxshi ko‘rmoq, hushidan ketmoq',
	},
	{ id: 99, tr: 'beslenmek', uz: 'ovqatlanmoq' },
	{ id: 100, tr: 'bilmek', uz: 'bilmoq' },
	{ id: 101, tr: 'binmek', uz: 'minmoq' },
	{ id: 102, tr: 'biriktirmek', uz: 'yig‘moq' },
	{ id: 103, tr: 'bitmek', uz: 'tugamoq' },
	{ id: 104, tr: 'buluşmak', uz: 'topishmoq, ko‘rishmoq, uchrashmoq' },
	{ id: 105, tr: 'çalışmak', uz: 'ishlamoq' },
	{ id: 106, tr: 'çıkmak', uz: 'chiqmoq' },
	{ id: 107, tr: 'demek', uz: 'demoq' },
	{ id: 108, tr: 'ders çalışmak', uz: 'dars tayyorlamoq' },
	{ id: 109, tr: 'dinlemek', uz: 'tinglamoq' },
	{ id: 110, tr: 'dinlenmek', uz: 'dam olmoq' },
	{ id: 111, tr: 'dolaşmak', uz: 'aylanmoq' },
	{ id: 112, tr: 'dönmek', uz: 'qaytmoq' },
	{ id: 113, tr: 'durmak', uz: 'turmoq' },
	{ id: 114, tr: 'duş almak', uz: 'dush qabul qilmoq' },
	{ id: 115, tr: 'fotoğraf çekmek', uz: 'rasmga olmoq' },
	{ id: 116, tr: 'çekmek', uz: 'tortmoq' },
	{ id: 117, tr: 'geçmek', uz: 'o‘tmoq' },
	{ id: 118, tr: 'gezmek', uz: 'kezmoq, sayr qilmoq' },
	{ id: 119, tr: 'girmek', uz: 'kirmoq' },
	{ id: 120, tr: 'gitmek', uz: 'ketmoq' },
	{ id: 121, tr: 'hazırlamak', uz: 'tayyorlamoq' },
	{ id: 122, tr: 'hazırlanmak', uz: 'tayyorlanmoq' },
	{ id: 123, tr: 'hoşlanmak', uz: 'yoqtirmoq' },
	{ id: 124, tr: 'internete girmek', uz: 'internetga kirmoq' },
	{ id: 125, tr: 'izlemek', uz: 'kuzatmoq' },
	{ id: 126, tr: 'kahvaltı etmek', uz: 'nonushta qilmoq' },
	{ id: 127, tr: 'kalkmak', uz: 'turmoq, qo‘zg‘almoq' },
	{ id: 128, tr: 'kalmak', uz: 'qolmoq' },
	{ id: 129, tr: 'kapatmak', uz: 'yopmoq' },
	{ id: 130, tr: 'kontrol etmek', uz: 'nazorat qilmoq' },
	{ id: 131, tr: 'konuşmak', uz: 'gaplashmoq' },
	{ id: 132, tr: 'korkmak', uz: 'qo‘rqmoq' },
	{ id: 133, tr: 'koşmak', uz: 'yugurmoq' },
	{ id: 134, tr: 'koymak', uz: 'qo‘ymoq' },
	{ id: 135, tr: 'kullanmak', uz: 'foydalanmoq, qo‘llanmoq' },
	{ id: 136, tr: 'nefret etmek', uz: 'nafratlanmoq' },
	{ id: 137, tr: 'okumak', uz: 'o‘qimoq' },
	{ id: 138, tr: 'oturmak', uz: 'o‘tirmoq' },
	{ id: 139, tr: 'oynamak', uz: 'o‘ynamoq' },
	{ id: 140, tr: 'öğrenmek', uz: 'o‘rganmoq' },
	{ id: 141, tr: 'özlemek', uz: 'sog‘inmoq' },
	{ id: 142, tr: 'para çekmek', uz: 'pul yechib olish' },
	{ id: 143, tr: 'pişirmek', uz: 'pishirmoq' },
	{ id: 144, tr: 'saç kestirmek', uz: 'sochini kestirmoq' },
	{ id: 145, tr: 'sanmak', uz: 'deb o‘ylamoq' },
	{ id: 146, tr: 'sevmek', uz: 'sevmoq' },
	{ id: 147, tr: 'sıkılmak', uz: 'zerikmoq' },
	{ id: 148, tr: 'sohbet etmek', uz: 'suhbat qilmoq' },
	{ id: 149, tr: 'sormak', uz: 'so‘ramoq' },
	{ id: 150, tr: 'söylemek', uz: 'demoq' },
	{ id: 151, tr: 'spor yapmak', uz: 'sport bilan shug‘ullanmoq' },
	{ id: 152, tr: 'stres atmak', uz: 'stresni yoqotish, tinchlanmoq' },
	{ id: 153, tr: 'tanımak', uz: 'tanimoq' },
	{ id: 154, tr: 'tanışmak', uz: 'tanishmoq' },
	{ id: 155, tr: 'tekrar etmek', uz: 'takrorlamoq, takror etmoq' },
	{ id: 156, tr: 'temizlemek', uz: 'tozalamoq' },
	{ id: 157, tr: 'tırmanmak', uz: 'tirmashmoq' },
	{ id: 158, tr: 'uyumak', uz: 'uxlamoq' },
	{ id: 159, tr: 'uzanmak', uz: 'uzanmoq' },
	{ id: 160, tr: 'varmak', uz: 'bormoq' },
	{ id: 161, tr: 'vermek', uz: 'bermoq' },
	{ id: 162, tr: 'yapmak', uz: 'qilmoq' },
	{ id: 163, tr: 'yardım etmek', uz: 'yordam qilmoq' },
	{ id: 164, tr: 'yardım istemek', uz: 'yordam so‘ramoq, yordam istamoq' },
	{ id: 165, tr: 'yaşamak', uz: 'yashamoq' },
	{ id: 166, tr: 'yatmak', uz: 'yotmoq' },
	{ id: 167, tr: 'yazmak', uz: 'yozmoq' },
	{ id: 168, tr: 'yemek', uz: 'yemoq' },
	{ id: 169, tr: 'yorulmak', uz: 'charchamoq' },
	{ id: 170, tr: 'yürümek', uz: 'yurmoq' },
	{ id: 171, tr: 'yüzmek', uz: 'suzmoq' },
	{ id: 172, tr: 'Bol bol', uz: 'ko‘p-ko‘p' },
	{ id: 173, tr: 'İnşallah', uz: 'xudo xohlasa' },
]
