export const a2WordsUnit3 = [
	{ id: 1, tr: 'ahşap', uz: 'yog‘och' },
	{ id: 2, tr: 'aniden', uz: 'to‘satdan, birdaniga' },
	{ id: 3, tr: 'asker', uz: 'askar' },
	{ id: 4, tr: 'Avrupa', uz: 'Yevropa' },
	{ id: 5, tr: 'baharatlı', uz: 'ziravorli' },
	{ id: 6, tr: 'bal', uz: 'asal' },
	{ id: 7, tr: 'bambu', uz: 'bambuk' },
	{ id: 8, tr: 'başbakan', uz: 'bosh vazir' },
	{ id: 9, tr: 'belediye', uz: 'hokimiyat' },
	{ id: 10, tr: 'bölge', uz: 'mintaqa, hudud' },
	{ id: 11, tr: 'bülbül', uz: 'bulbul' },
	{ id: 12, tr: 'çadır', uz: 'chodir' },
	{ id: 13, tr: 'çekirdek', uz: 'pista' },
	{ id: 14, tr: 'çevre', uz: 'atrof-muhit' },
	{ id: 15, tr: 'çiftçi', uz: 'dehqon' },
	{ id: 16, tr: 'dağ', uz: 'tog‘' },
	{ id: 17, tr: 'dışkı', uz: 'najas,' },
	{ id: 18, tr: 'dizi', uz: 'serial' },
	{ id: 19, tr: 'doğum günü', uz: 'tug‘ilgan kun' },
	{
		id: 20,
		tr: 'döner',
		uz: 'aylanadigan (donar taomining nomi shundan olingan)',
	},
	{ id: 21, tr: 'eldiven', uz: 'qo‘lqop' },
	{ id: 22, tr: 'eş', uz: 'turmush o‘rtoq, hamroh' },
	{ id: 23, tr: 'etkinlik', uz: 'faoliyat, mashg‘ulot' },
	{ id: 24, tr: 'ev planı', uz: 'uy rejasi' },
	{ id: 25, tr: 'fal', uz: 'fol' },
	{ id: 26, tr: 'faydalı', uz: 'foydali' },
	{ id: 27, tr: 'ferah', uz: 'keng' },
	{ id: 28, tr: 'festival', uz: 'festival' },
	{ id: 29, tr: 'gelenek', uz: 'an’ana' },
	{ id: 30, tr: 'gösteri', uz: 'tomosha' },
	{ id: 31, tr: 'güneşli', uz: 'quyoshli' },
	{ id: 32, tr: 'harika', uz: 'ajoyib' },
	{ id: 33, tr: 'hastane', uz: 'shifoxona' },
	{ id: 34, tr: 'hava', uz: 'havo' },
	{ id: 35, tr: 'hayal', uz: 'orzu' },
	{ id: 36, tr: 'hediye', uz: 'sovg‘a' },
	{ id: 37, tr: 'ılık', uz: 'iliq' },
	{ id: 38, tr: 'icat', uz: 'kashfiyot, ijod' },
	{ id: 39, tr: 'inatçı', uz: 'qaysar, o‘r' },
	{ id: 40, tr: 'izleyici', uz: 'tomoshabin' },
	{ id: 41, tr: 'jimnastik', uz: 'gimnastika' },
	{ id: 42, tr: 'kaban', uz: 'palto' },
	{ id: 43, tr: 'kampanya', uz: 'kampaniya' },
	{ id: 44, tr: 'kar', uz: 'qor' },
	{ id: 45, tr: 'katedral', uz: 'ibodatxona' },
	{ id: 46, tr: 'kazak', uz: 'sviter' },
	{ id: 47, tr: 'kıyı', uz: 'qirg‘oq' },
	{ id: 48, tr: 'kıymet', uz: 'qiymat' },
	{ id: 49, tr: 'klozet', uz: 'shkaf' },
	{ id: 50, tr: 'mahalli', uz: 'mahalliy' },
	{ id: 51, tr: 'makyaj', uz: 'pardoz' },
	{ id: 52, tr: 'merasim', uz: 'marosim' },
	{ id: 53, tr: 'mercimek', uz: 'yasmiq (чечевица)' },
	{ id: 54, tr: 'kristal', uz: 'kristall' },
	{ id: 55, tr: 'kurnaz', uz: 'ayyor' },
	{ id: 56, tr: 'kuruyemiş', uz: 'quruq yemaklar,quruq mevalar' },
	{ id: 57, tr: 'kültür', uz: 'madaniyat' },
	{ id: 58, tr: 'lacivert', uz: 'lojuvard, ko‘k' },
	{ id: 59, tr: 'magazin', uz: 'jurnal' },
	{ id: 60, tr: 'mağaza', uz: 'do‘kon' },
	{ id: 61, tr: 'meşhur', uz: 'mashhur' },
	{ id: 62, tr: 'meşgul', uz: 'band' },
	{ id: 63, tr: 'metre', uz: 'metr' },
	{ id: 64, tr: 'mineral', uz: 'mineral' },
	{ id: 65, tr: 'mizaç', uz: 'mijoz' },
	{ id: 66, tr: 'mucit', uz: 'ixtirochi' },
	{ id: 67, tr: 'muhteşem', uz: 'muhtasham' },
	{ id: 68, tr: 'müdür', uz: 'mudir, direktor' },
	{ id: 69, tr: 'okyanus', uz: 'okean' },
	{ id: 70, tr: 'ödül', uz: 'mukofot' },
	{ id: 71, tr: 'pano', uz: 'panel' },
	{ id: 72, tr: 'politika', uz: 'siyosat' },
	{ id: 73, tr: 'porsiyon', uz: 'miqdor (portsiya)' },
	{ id: 74, tr: 'protein', uz: 'oqsil' },
	{ id: 75, tr: 'puan', uz: 'ball' },
	{ id: 76, tr: 'radyo dalgası', uz: 'radio to‘lqini' },
	{ id: 77, tr: 'reçete', uz: 'dorilar yozilgan ro‘yxat(retsept)' },
	{ id: 78, tr: 'romancı', uz: 'roman yozuvchi' },
	{ id: 79, tr: 'romantik', uz: 'romantik' },
	{ id: 80, tr: 'satış', uz: 'sotish' },
	{ id: 81, tr: 'sene', uz: 'yil' },
	{ id: 82, tr: 'sıradan', uz: 'oddiy, hamma qatori' },
	{ id: 83, tr: 'sinyal', uz: 'signal' },
	{ id: 84, tr: 'siyah', uz: 'qora' },
	{ id: 85, tr: 'takım', uz: 'jamoa' },
	{ id: 86, tr: 'takma', uz: 'taxallus' },
	{ id: 87, tr: 'tavan', uz: 'shift' },
	{ id: 88, tr: 'tavşan', uz: 'quyon' },
	{ id: 89, tr: 'teleskop', uz: 'teleskop' },
	{ id: 90, tr: 'toplantı', uz: 'majlis' },
	{ id: 91, tr: 'tür', uz: 'tur, nav, xil' },
	{ id: 92, tr: 'ünvan', uz: 'unvon' },
	{ id: 93, tr: 'usta', uz: 'usta' },
	{ id: 94, tr: 'vasıta', uz: 'vosita' },
	{ id: 95, tr: 'yazar', uz: 'yozuvchi' },
	{ id: 96, tr: 'yolculuk', uz: 'sayohat' },
	{ id: 97, tr: 'yöresel', uz: 'mahalliy' },
	{ id: 98, tr: 'zencefil', uz: 'zanjabil' },
	{ id: 99, tr: 'adım atmak', uz: 'qadam tashlamoq' },
	{ id: 100, tr: 'affetmek', uz: 'kechirmoq' },
	{ id: 101, tr: 'atanmak', uz: 'tayinlanmoq' },
	{ id: 102, tr: 'bastırmak', uz: 'bostirmoq' },
	{ id: 103, tr: 'başvurmak', uz: 'topshirmoq' },
	{ id: 104, tr: 'doğmak', uz: 'tug‘ilmoq' },
	{ id: 105, tr: 'düşürmek', uz: 'tushirmoq' },
	{ id: 106, tr: 'gönüllü olmak', uz: 'ko‘ngillibo‘lmoq' },
	{ id: 107, tr: 'ilerlemek', uz: 'ilgarilamoq,rivojlanmoq, davom etmoq' },
	{
		id: 108,
		tr: 'incelemek',
		uz: 'mayda detallarigacha tadqiq qilmoq, tekshirmoq',
	},
	{ id: 109, tr: 'katılmak', uz: 'qo‘shilmoq, ishtiroketmoq' },
	{ id: 110, tr: 'kazanmak', uz: 'g‘alaba qozonmoq' },
	{ id: 111, tr: 'keşfetmek', uz: 'kashf qilmoq' },
	{
		id: 112,
		tr: 'mezun olmak',
		uz: 'bitirmoq (litsey, universitetni tugatmoq)',
	},
	{ id: 113, tr: 'tüketmek', uz: 'iste’mol qilmoq' },
	{ id: 114, tr: 'ünlü olmak', uz: 'mashhur bo‘lmoq' },
	{ id: 115, tr: 'vazgeçmek', uz: 'voz kechmoq' },
	{ id: 116, tr: 'yerleşmek', uz: 'joylashmoq' },
	{ id: 117, tr: 'yayımlamak', uz: 'nashr qilmoq' },
]
