export const a2WordsUnit2 = [
	{ id: 1, tr: 'aksiyon', uz: 'jangovar (filmga nisbatan)' },
	{ id: 2, tr: 'animasyon', uz: 'animatsiyon' },
	{ id: 3, tr: 'as', uz: 'as (bir ishning ustasi)' },
	{ id: 4, tr: 'başrol', uz: 'bosh rol' },
	{ id: 5, tr: 'belgesel', uz: 'hujjatli (filmga nisbatan)' },
	{ id: 6, tr: 'beslenme', uz: 'oziqlanish, ovqatlanish' },
	{ id: 7, tr: 'beyaz', uz: 'oq' },
	{ id: 8, tr: 'bilgin', uz: 'olim' },
	{ id: 9, tr: 'bolca', uz: 'mo‘l' },
	{ id: 10, tr: 'bordo', uz: 'to‘q qizil (бордовый)' },
	{ id: 11, tr: 'buluş', uz: 'kashfiyot' },
	{ id: 12, tr: 'cömert', uz: 'saxiy' },
	{ id: 13, tr: 'çavdar', uz: 'javdar' },
	{ id: 14, tr: 'çığ', uz: 'qor ko‘chkisi' },
	{ id: 15, tr: 'çiğ', uz: 'xom' },
	{ id: 16, tr: 'çizgi film', uz: 'multfilm' },
	{ id: 17, tr: 'demokrasi', uz: 'demokratiya' },
	{ id: 18, tr: 'deney', uz: 'tajriba' },
	{ id: 19, tr: 'derbi', uz: 'derbi (sport uchrashuvi)' },
	{ id: 20, tr: 'dram', uz: 'drama (filmga nisbatan)' },
	{ id: 21, tr: 'egzersiz', uz: 'jismoniy mashqlar' },
	{ id: 22, tr: 'ekonomi', uz: 'iqtisodiyot' },
	{ id: 23, tr: 'emekli', uz: 'nafaqaxo‘r' },
	{ id: 24, tr: 'esnek', uz: 'o‘zgaruvchan, egiluvchan' },
	{ id: 25, tr: 'fare', uz: 'sichqon' },
	{
		id: 26,
		tr: 'fırsatçı',
		uz: 'fursatchi, fursatdan foydalanib qoladigan odam',
	},
	{ id: 27, tr: 'gazetecilik', uz: 'jurnalistika' },
	{ id: 28, tr: 'gece', uz: 'kecha' },
	{ id: 29, tr: 'gerilim', uz: 'triller (filmga nisbatan)' },
	{ id: 30, tr: 'gündüz', uz: 'kunduz' },
	{ id: 31, tr: 'hayalci', uz: 'xayolparast' },
	{ id: 32, tr: 'hırsız', uz: 'o‘g‘ri' },
	{ id: 33, tr: 'hizmetçi', uz: 'xizmatkor' },
	{ id: 34, tr: 'hükümdar', uz: 'hukmdor' },
	{ id: 35, tr: 'idareci', uz: 'ma’mur' },
	{ id: 36, tr: 'ihtiyaç', uz: 'ehtiyoj' },
	{ id: 37, tr: 'iletişim', uz: 'aloqa' },
	{ id: 38, tr: 'ilginç', uz: 'qiziqarli' },
	{ id: 39, tr: 'ilk', uz: 'birinchi' },
	{ id: 40, tr: 'kahkaha', uz: 'qahqaha' },
	{ id: 41, tr: 'kahraman', uz: 'qahramon' },
	{ id: 42, tr: 'kalsiyum', uz: 'kalsiy' },
	{ id: 43, tr: 'kampanya', uz: 'kampaniya' },
	{ id: 44, tr: 'kanat', uz: 'qanot' },
	{ id: 45, tr: 'kaplumbağa', uz: 'toshbaqa' },
	{ id: 46, tr: 'kemik', uz: 'suyak' },
	{ id: 47, tr: 'kepek', uz: 'kepak' },
	{ id: 48, tr: 'kırmızı', uz: 'qizil' },
	{ id: 49, tr: 'kolesterol', uz: 'xolesterin' },
	{ id: 50, tr: 'komutan', uz: 'qo‘mondon' },
	{ id: 51, tr: 'konforlu', uz: 'qulay' },
	{ id: 52, tr: 'kongre', uz: 'kongress' },
	{ id: 53, tr: 'koyun', uz: 'qo‘y' },
	{ id: 54, tr: 'kristal', uz: 'kristall' },
	{ id: 55, tr: 'kurnaz', uz: 'ayyor' },
	{ id: 56, tr: 'kuruyemiş', uz: 'quruq yemaklar, quruq mevalar' },
	{ id: 57, tr: 'kültür', uz: 'madaniyat' },
	{ id: 58, tr: 'lacivert', uz: 'lojuvard, ko‘k' },
	{ id: 59, tr: 'magazin', uz: 'jurnal' },
	{ id: 60, tr: 'mağaza', uz: 'do‘kon' },
	{ id: 61, tr: 'meşhur', uz: 'mashhur' },
	{ id: 62, tr: 'meşgul', uz: 'band' },
	{ id: 63, tr: 'metre', uz: 'metr' },
	{ id: 64, tr: 'mineral', uz: 'mineral' },
	{ id: 65, tr: 'mizaç', uz: 'mijoz' },
	{ id: 66, tr: 'mucit', uz: 'ixtirochi' },
	{ id: 67, tr: 'muhteşem', uz: 'muhtasham' },
	{ id: 68, tr: 'müdür', uz: 'mudir, direktor' },
	{ id: 69, tr: 'okyanus', uz: 'okean' },
	{ id: 70, tr: 'ödül', uz: 'mukofot' },
	{ id: 71, tr: 'pano', uz: 'panel' },
	{ id: 72, tr: 'politika', uz: 'siyosat' },
	{ id: 73, tr: 'porsiyon', uz: 'miqdor (portsiya)' },
	{ id: 74, tr: 'protein', uz: 'oqsil' },
	{ id: 75, tr: 'puan', uz: 'ball' },
	{ id: 76, tr: 'radyo dalgası', uz: 'radio to‘lqini' },
	{ id: 77, tr: 'reçete', uz: 'dorilar yozilgan ro‘yxat (retsept)' },
	{ id: 78, tr: 'romancı', uz: 'roman yozuvchi' },
	{ id: 79, tr: 'romantik', uz: 'romantik' },
	{ id: 80, tr: 'satış', uz: 'sotish' },
	{ id: 81, tr: 'sene', uz: 'yil' },
	{ id: 82, tr: 'sıradan', uz: 'oddiy, hamma qatori' },
	{ id: 83, tr: 'sinyal', uz: 'signal' },
	{ id: 84, tr: 'siyah', uz: 'qora' },
	{ id: 85, tr: 'takım', uz: 'jamoa' },
	{ id: 86, tr: 'takma', uz: 'taxallus' },
	{ id: 87, tr: 'tavan', uz: 'shift' },
	{ id: 88, tr: 'tavşan', uz: 'quyon' },
	{ id: 89, tr: 'teleskop', uz: 'teleskop' },
	{ id: 90, tr: 'toplantı', uz: 'majlis' },
	{ id: 91, tr: 'tür', uz: 'tur, nav, xil' },
	{ id: 92, tr: 'ünvan', uz: 'unvon' },
	{ id: 93, tr: 'usta', uz: 'usta' },
	{ id: 94, tr: 'vasıta', uz: 'vosita' },
	{ id: 95, tr: 'yazar', uz: 'yozuvchi' },
	{ id: 96, tr: 'yolculuk', uz: 'sayohat' },
	{ id: 97, tr: 'yöresel', uz: 'mahalliy' },
	{ id: 98, tr: 'zencefil', uz: 'zanjabil' },
	{ id: 99, tr: 'adım atmak', uz: 'qadam tashlamoq' },
	{ id: 100, tr: 'affetmek', uz: 'kechirmoq' },
	{ id: 101, tr: 'atanmak', uz: 'tayinlanmoq' },
	{ id: 102, tr: 'bastırmak', uz: 'bostirmoq' },
	{ id: 103, tr: 'başvurmak', uz: 'topshirmoq' },
	{ id: 104, tr: 'doğmak', uz: 'tug‘ilmoq' },
	{ id: 105, tr: 'düşürmek', uz: 'tushirmoq' },
	{ id: 106, tr: 'gönüllü olmak', uz: 'ko‘ngilli bo‘lmoq' },
	{ id: 107, tr: 'ilerlemek', uz: 'ilgarilamoq, rivojlanmoq, davom etmoq' },
	{
		id: 108,
		tr: 'incelemek',
		uz: 'mayda detallarigacha tadqiq qilmoq, tekshirmoq',
	},
	{ id: 109, tr: 'katılmak', uz: 'qo‘shilmoq, ishtirok etmoq' },
	{ id: 110, tr: 'kazanmak', uz: 'g‘alaba qozonmoq' },
	{ id: 111, tr: 'keşfetmek', uz: 'kashf qilmoq' },
	{
		id: 112,
		tr: 'mezun olmak',
		uz: 'bitirmoq (litsey, universitetni tugatmoq)',
	},
	{ id: 113, tr: 'tüketmek', uz: 'iste’mol qilmoq' },
	{ id: 114, tr: 'ünlü olmak', uz: 'mashhur bo‘lmoq' },
	{ id: 115, tr: 'vazgeçmek', uz: 'voz kechmoq' },
	{ id: 116, tr: 'yerleşmek', uz: 'joylashmoq' },
	{ id: 117, tr: 'yayımlamak', uz: 'nashr qilmoq' },
]
