export const a2WordsUnit1 = [
	{ id: 102, tr: 'ada', uz: 'orol' },
	{ id: 103, tr: 'akıllı', uz: 'aqlli' },
	{ id: 104, tr: 'altın', uz: 'oltin, tilla' },
	{ id: 105, tr: 'ana yemek', uz: 'asosiy taom' },
	{ id: 106, tr: 'apartman', uz: 'ko‘p qavatli uy' },
	{ id: 107, tr: 'aptal', uz: 'ahmoq' },
	{ id: 108, tr: 'âşık', uz: 'oshiq' },
	{ id: 109, tr: 'aşk', uz: 'sevgi' },
	{ id: 110, tr: 'avuç', uz: 'hovuch' },
	{ id: 111, tr: 'baklava', uz: 'baklava (shirinlik nomi)' },
	{ id: 112, tr: 'beyaz', uz: 'oq' },
	{ id: 113, tr: 'bez', uz: 'mato' },
	{ id: 114, tr: 'bıyık', uz: 'mo‘ylov' },
	{ id: 115, tr: 'biber', uz: 'qalampir' },
	{ id: 116, tr: 'bol', uz: 'ko‘p' },
	{ id: 117, tr: 'börek', uz: 'bo‘rek (turkcha qatlama)' },
	{ id: 118, tr: 'bulut', uz: 'bulut' },
	{ id: 119, tr: 'büfe', uz: 'bufet' },
	{ id: 120, tr: 'cadde', uz: 'ko‘cha (shoh ko‘cha)' },
	{ id: 121, tr: 'çikolata', uz: 'shokolad' },
	{ id: 122, tr: 'çim', uz: 'o‘t' },
	{ id: 123, tr: 'çizgi', uz: 'chiziq' },
	{ id: 124, tr: 'çöp', uz: 'chiqindi' },
	{ id: 125, tr: 'dalgalı', uz: 'to‘lqinli' },
	{ id: 126, tr: 'damar', uz: 'tomir' },
	{ id: 127, tr: 'demet', uz: 'bog‘, dasta, tutam' },
	{ id: 128, tr: 'dengesiz', uz: 'muvozanatsiz, beqaror' },
	{ id: 129, tr: 'dilim', uz: 'tilim' },
	{ id: 130, tr: 'dosdoğru', uz: 'to‘ppa-to‘g‘ri' },
	{ id: 131, tr: 'dürüst', uz: 'to‘g‘riso‘z, rostgo‘y' },
	{ id: 132, tr: 'düşünceli', uz: 'fikriga ega; o‘ylab ish qiladigan' },
	{ id: 133, tr: 'düzenli', uz: 'tartibli' },
	{ id: 134, tr: 'ecza dolabı', uz: 'dori shkafi' },
	{ id: 135, tr: 'ela', uz: 'ola, qo‘ng‘ir' },
	{ id: 136, tr: 'emir', uz: 'buyruq' },
	{ id: 137, tr: 'enerjik', uz: 'energiyaga to‘la' },
	{ id: 138, tr: 'esprili', uz: 'hazilkash' },
	{ id: 139, tr: 'et', uz: 'go‘sht' },
	{ id: 140, tr: 'faydalı', uz: 'foydali' },
	{ id: 141, tr: 'gece', uz: 'kecha, tun' },
	{ id: 142, tr: 'gerekli', uz: 'kerakli' },
	{ id: 143, tr: 'gökyüzü', uz: 'osmon' },
	{ id: 144, tr: 'gözlük', uz: 'ko‘zoynak' },
	{ id: 145, tr: 'güler yüzlü', uz: 'ochiq chehrali' },
	{ id: 146, tr: 'güvenilir', uz: 'ishonchli' },
	{ id: 147, tr: 'harika', uz: 'ajoyib' },
	{ id: 148, tr: 'hayvan', uz: 'hayvon' },
	{ id: 149, tr: 'huzurlu', uz: 'tinch, huzurli' },
	{ id: 150, tr: 'ihtiyaç', uz: 'kerak, ehtiyoj' },
	{ id: 151, tr: 'ilaç', uz: 'dori' },
	{ id: 152, tr: 'inatçı', uz: 'o‘jar, qaysar' },
	{ id: 153, tr: 'istek', uz: 'istak, xohish' },
	{ id: 154, tr: 'kadayıf', uz: 'kadayıf (turkchaingichka lag‘mon)' },
	{ id: 155, tr: 'kadeh', uz: 'qadah' },
	{ id: 156, tr: 'kap', uz: 'idish' },
	{ id: 157, tr: 'kapıcı', uz: 'qorovul' },
	{ id: 158, tr: 'karabiber', uz: 'murch' },
	{ id: 159, tr: 'karınca', uz: 'chumoli' },
	{ id: 160, tr: 'karizmatik', uz: 'xarizmatik' },
	{ id: 161, tr: 'karpuz', uz: 'tarvuz' },
	{ id: 162, tr: 'kâse', uz: 'kosa' },
	{
		id: 163,
		tr: 'kekik',
		uz: 'urug‘i ziravor sifatida ishlatiladigan o‘simlik(тимьян)',
	},
	{ id: 164, tr: 'kemer', uz: 'kamar' },
	{ id: 165, tr: 'kenar', uz: 'burchak, qirg‘oq, yon' },
	{ id: 166, tr: 'kısım', uz: 'qism' },
	{ id: 167, tr: 'kıyma', uz: 'qiyma' },
	{ id: 168, tr: 'kızıl', uz: 'qizil' },
	{ id: 169, tr: 'kilogram', uz: 'kilogramm' },
	{ id: 170, tr: 'klinik', uz: 'klinika' },
	{ id: 171, tr: 'konu', uz: 'mavzu' },
	{ id: 172, tr: 'korkak', uz: 'qo‘rqoq' },
	{ id: 173, tr: 'köfte', uz: 'kotlet' },
	{ id: 174, tr: 'kurabiye', uz: 'pechenye' },
	{
		id: 175,
		tr: 'kuşbaşı',
		uz: 'kichik bir qushning boshi kattaligida bo‘lgan (o‘lchov)',
	},
	{ id: 176, tr: 'kutsal', uz: 'muqaddas' },
	{ id: 177, tr: 'küp', uz: 'kub (geometrik shakl)' },
	{ id: 178, tr: 'lahmacun', uz: 'lahmajun (Turk' },
	{ id: 179, tr: 'levha', uz: 'lavha (tablo)' },
	{ id: 180, tr: 'lezzetli', uz: 'mazali' },
	{ id: 181, tr: 'lokum', uz: 'turkcha shirinlik,marmelad' },
	{ id: 182, tr: 'makarna', uz: 'makaron' },
	{ id: 183, tr: 'malzeme', uz: 'mahsulot' },
	{ id: 184, tr: 'maydanoz', uz: 'petrushka ko‘kati' },
	{ id: 185, tr: 'menü', uz: 'taomnoma (menyu)' },
	{ id: 186, tr: 'meraklı', uz: 'qiziquvchan' },
	{ id: 187, tr: 'meslek', uz: 'kasb' },
	{ id: 188, tr: 'mesut', uz: 'baxtli' },
	{ id: 189, tr: 'miktar', uz: 'miqdor' },
	{ id: 190, tr: 'mutlaka', uz: 'mutlaqo' },
	{ id: 191, tr: 'müşteri', uz: 'xaridor' },
	{ id: 192, tr: 'müze', uz: 'muzey' },
	{ id: 193, tr: 'naz', uz: 'noz-karashma' },
	{ id: 194, tr: 'neşeli', uz: 'quvnoq' },
	{ id: 195, tr: 'otopark', uz: 'avtopark' },
	{ id: 196, tr: 'öneri', uz: 'taklif' },
	{ id: 197, tr: 'patlıcan', uz: 'baqlajon' },
	{ id: 198, tr: 'perde', uz: 'parda' },
	{ id: 199, tr: 'peynir', uz: 'pishloq' },
	{ id: 200, tr: 'pizza', uz: 'pitsa' },
	{ id: 201, tr: 'porsiyon', uz: 'qism (portsiya)' },
	{ id: 202, tr: 'profil', uz: 'profil' },
	{ id: 203, tr: 'prospektüs', uz: 'prospekt' },
	{ id: 204, tr: 'rüya', uz: 'tush' },
	{ id: 205, tr: 'rüzgâr', uz: 'shamol' },
	{ id: 206, tr: 'sabır', uz: 'sabr' },
	{ id: 207, tr: 'sakal', uz: 'soqol' },
	{ id: 208, tr: 'salata', uz: 'salat' },
	{ id: 209, tr: 'salyangoz', uz: 'shilliqqurt,chig‘anoq' },
	{ id: 210, tr: 'saman', uz: 'somon' },
	{ id: 211, tr: 'saygı', uz: 'hurmat' },
	{ id: 212, tr: 'sevgi', uz: 'sevgi' },
	{ id: 213, tr: 'sevimli', uz: 'yoqimli' },
	{ id: 214, tr: 'sıvı', uz: 'suyuq' },
	{
		id: 215,
		tr: 'sifon',
		uz: 'santexnik quvur (rokovinadan qo‘lansa hid chiqmasligi uchun o‘rnatiladigan egiluvchan quvur)',
	},
	{ id: 216, tr: 'sigara', uz: 'sigaret' },
	{ id: 217, tr: 'sipariş', uz: 'buyurtma' },
	{ id: 218, tr: 'site', uz: 'sayt' },
	{ id: 219, tr: 'soğan', uz: 'piyoz' },
	{ id: 220, tr: 'soğuk', uz: 'sovuq' },
	{ id: 221, tr: 'sosyal paylaşım', uz: 'social sharing' },
	{ id: 222, tr: 'su', uz: 'suv' },
	{ id: 223, tr: 'şarap', uz: 'vino' },
	{ id: 224, tr: 'şeker', uz: 'shakar' },
	{ id: 225, tr: 'şirin', uz: 'yoqimli' },
	{ id: 226, tr: 'şiş', uz: 'shish, six' },
	{ id: 227, tr: 'tane', uz: 'dona' },
	{ id: 228, tr: 'tarif', uz: 'tarif' },
	{ id: 229, tr: 'tatlı', uz: 'shirin' },
	{ id: 230, tr: 'tava', uz: 'tova' },
	{ id: 231, tr: 'tavsiye', uz: 'tavsiya' },
	{ id: 232, tr: 'tecrübe', uz: 'tajriba' },
	{ id: 233, tr: 'tek', uz: 'bitta, yagona' },
	{ id: 234, tr: 'ten', uz: 'teri' },
	{ id: 235, tr: 'tramvay', uz: 'tramvay' },
	{ id: 236, tr: 'tuvalet', uz: 'hojatxona' },
	{ id: 237, tr: 'tuz', uz: 'tuz' },
	{ id: 238, tr: 'uyarı', uz: 'ogohlantirish' },
	{ id: 239, tr: 'veteriner', uz: 'veterinar' },
	{ id: 240, tr: 'yağ', uz: 'yog‘' },
	{ id: 241, tr: 'yağmur', uz: 'yomg‘ir' },
	{ id: 242, tr: 'yarar', uz: 'foyda' },
	{ id: 243, tr: 'yarışma', uz: 'musobaqa' },
	{ id: 244, tr: 'yaşam', uz: 'hayot, umr' },
	{ id: 245, tr: 'yeterince', uz: 'yetarlicha' },
	{ id: 246, tr: 'yorgan', uz: 'choyshab' },
	{ id: 247, tr: 'yumurta', uz: 'tuxum' },
	{ id: 248, tr: 'yüksek', uz: 'yuqori, baland' },
	{ id: 249, tr: 'zarar', uz: 'zarar' },
	{ id: 250, tr: 'acele etmek', uz: 'shoshilmoq' },
	{ id: 251, tr: 'anlatmak', uz: 'tushuntirmoq' },
	{ id: 252, tr: 'bağlamak', uz: 'bog‘lamoq' },
	{ id: 253, tr: 'basmak', uz: 'chop etmoq, bosmoq' },
	{ id: 254, tr: 'beğenmek', uz: 'yoqtirmoq' },
	{ id: 255, tr: 'beslenmek', uz: 'ovqatlanmoq' },
	{ id: 256, tr: 'bıkmak', uz: 'bezor bo‘lmoq' },
	{ id: 257, tr: 'bölmek', uz: 'bo‘lmoq' },
	{ id: 258, tr: 'çağırmak', uz: 'chaqirmoq, taklifetmoq' },
	{ id: 259, tr: 'çekmek', uz: 'tortmoq, sudramoq' },
	{ id: 260, tr: 'çırpmak', uz: 'chapak chalmoq, taomni qorishtirmoq' },
	{ id: 261, tr: 'dizmek', uz: 'tizmoq, tekislamoq' },
	{ id: 262, tr: 'doğramak', uz: 'to‘g‘ramoq' },
	{ id: 263, tr: 'doldurmak', uz: 'to‘ldirmoq' },
	{ id: 264, tr: 'dökmek', uz: 'to‘kmoq, quymoq' },
	{ id: 265, tr: 'duymak', uz: 'eshitmoq, tuymoq' },
	{ id: 266, tr: 'düşünmek', uz: 'o‘ylamoq' },
	{ id: 267, tr: 'düzenlemek', uz: 'tartibga solmoq' },
	{ id: 268, tr: 'eklemek', uz: 'qo‘shmoq, solmoq' },
	{ id: 269, tr: 'geç kalmak', uz: 'kech qolmoq' },
	{ id: 270, tr: 'getirmek', uz: 'olib kelmoq' },
	{ id: 271, tr: 'göndermek', uz: 'yubormoq,jo‘natmoq' },
	{ id: 272, tr: 'hapşırmak', uz: 'aksirmoq' },
	{ id: 273, tr: 'haşlamak', uz: 'qaynatib pishirmoq' },
	{ id: 274, tr: 'hatırlamak', uz: 'eslamoq' },
	{ id: 275, tr: 'ısmarlamak', uz: 'buyurtirmoq; siylamoq' },
	{ id: 276, tr: 'ihmal etmek', uz: 'e’tiborsizqoldirmoq' },
	{ id: 277, tr: 'ilave etmek', uz: 'qo‘shmoq' },
	{ id: 278, tr: 'ilerlemek', uz: 'ilgarilamoq,rivojlanmoq' },
	{ id: 279, tr: 'isyan etmek', uz: 'isyon qilmoq' },
	{ id: 280, tr: 'işaretlemek', uz: 'belgilamoq' },
	{ id: 281, tr: 'itmek', uz: 'turtmoq' },
	{ id: 282, tr: 'karıştırmak', uz: 'aralashtirmoq' },
	{ id: 283, tr: 'kavga etmek', uz: 'janjal qilmoq' },
	{ id: 284, tr: 'kaynatmak', uz: 'qaynatmoq' },
	{ id: 285, tr: 'kesmek', uz: 'kesmoq' },
	{ id: 286, tr: 'kızartmak', uz: 'qizartirmoq' },
	{ id: 287, tr: 'kopmak', uz: 'uzulmoq, uzmoq' },
	{ id: 288, tr: 'kızmak', uz: 'qizimoq, achchig‘lanmoq' },
	{ id: 289, tr: 'koymak', uz: 'qo‘ymoq' },
	{ id: 290, tr: 'merak etmek', uz: 'qiziqmoq, xavotir olmoq' },
	{ id: 291, tr: 'numaralandırmak', uz: 'raqamlamoq' },
	{ id: 292, tr: 'oluşturmak', uz: 'yaratmoq' },
	{ id: 293, tr: 'önermek', uz: 'taklif qilmoq' },
	{
		id: 294,
		tr: 'özen göstermek',
		uz: 'ishiga bor e‘tibor va g‘ayratini ko‘rsatmoq',
	},
	{ id: 295, tr: 'park etmek', uz: 'avtoulovinijoylashtirmoq' },
	{ id: 296, tr: 'pişirmek', uz: 'pishirmoq' },
	{ id: 297, tr: 'rendelemek', uz: 'qirg‘ichdanchiqarmoq' },
	{ id: 298, tr: 'saklamak', uz: 'saqlamoq, yashirmoq' },
	{ id: 299, tr: 'sıralamak', uz: 'navbatga qoy‘ymoq, safga tizmoq' },
	{ id: 300, tr: 'silmek', uz: 'tozalamoq, o‘chirmoq' },
	{ id: 301, tr: 'sipariş vermek', uz: 'buyurtma bermoq' },
	{ id: 302, tr: 'süzmek', uz: 'suzmoq (taomni)' },
	{ id: 303, tr: 'tamamlamak', uz: 'tugatmoq' },
	{ id: 304, tr: 'tarif etmek', uz: 'tasvirlamoq' },
	{ id: 305, tr: 'tüketmek', uz: 'iste’mol qilmoq' },
	{ id: 306, tr: 'usanmak', uz: 'zerikkandan bezor bo‘lmoq' },
	{ id: 307, tr: 'uzatmak', uz: 'uzatmoq, cho‘zmoq' },
	{ id: 308, tr: 'yağmak', uz: 'yog‘moq' },
	{ id: 309, tr: 'yalan söylemek', uz: 'yolg‘ongapirmoq' },
	{ id: 310, tr: 'yerleştirmek', uz: 'joylashtirmoq' },
	{ id: 311, tr: 'zaman ayırmak', uz: 'vaqt ajratmoq' },
	{ id: 312, tr: 'ziyaret etmek', uz: 'ziyorat qilmoq' },
	{ id: 313, tr: 'Afiyet olsun!', uz: 'Yoqimli ishtaha!' },
	{ id: 314, tr: 'Çok yaşayın!', uz: 'Sog‘ bo‘ling!' },
	{ id: 315, tr: 'Elinize sağlık!', uz: 'Qo‘lingiz dardko‘rmasin!' },
	{ id: 16, tr: 'Hayırlı olsun!', uz: 'Xayrli bo‘lsin!' },
	{ id: 317, tr: 'Kolay gelsin!', uz: 'Omad tilaymiz!' },
]
