export const wordsUnit1 = [
	{ id: 1, tr: 'Ad, isim', uz: 'ism' },
	{ id: 2, tr: 'ağaç', uz: 'daraxt' },
	{ id: 3, tr: 'arkadaş', uz: 'do‘st' },
	{ id: 4, tr: 'anneler günü', uz: 'onalar kuni' },
	{ id: 5, tr: 'Afrika', uz: 'Afrika' },
	{ id: 6, tr: 'ağustos', uz: 'avgust' },
	{ id: 7, tr: 'alkol', uz: 'alkogol (spirt)' },
	{ id: 8, tr: 'akşam', uz: 'oqshom' },
	{ id: 9, tr: 'aktör', uz: 'aktyor' },
	{ id: 10, tr: 'Alman', uz: 'nemıs' },
	{ id: 11, tr: 'Almanya', uz: 'Germaniya' },
	{ id: 12, tr: 'Amerıka', uz: 'Amerika' },
	{ id: 13, tr: 'araba', uz: 'mashina (avtomobil)' },
	{ id: 14, tr: 'aralık', uz: 'dekabr' },
	{ id: 15, tr: 'Arap', uz: 'arab' },
	{ id: 16, tr: 'Arnavut', uz: 'Albaniya' },
	{ id: 17, tr: 'Arnavutluk', uz: 'alban' },
	{ id: 18, tr: 'Asya', uz: 'Osiyo' },
	{ id: 19, tr: 'Avrupa', uz: 'Yevropa' },
	{ id: 20, tr: 'avukat', uz: 'advokat' },
	{ id: 21, tr: 'Avustralya', uz: 'Avstraliya' },
	{ id: 22, tr: 'Avusturya', uz: 'Avstriya' },
	{ id: 23, tr: 'az', uz: 'kam, oz' },
	{ id: 24, tr: 'baba', uz: 'dada (ota)' },
	{ id: 25, tr: 'bahçe', uz: 'bog‘' },
	{ id: 26, tr: 'balık', uz: 'baliq' },
	{ id: 27, tr: 'balkon', uz: 'balkon' },
	{ id: 28, tr: 'banka', uz: 'bank' },
	{ id: 29, tr: 'banyo', uz: 'hammom (dush)' },
	{ id: 30, tr: 'bardak', uz: 'stakan' },
	{ id: 31, tr: 'bay', uz: 'janob' },
	{ id: 32, tr: 'bayan', uz: 'xonim' },
	{ id: 33, tr: 'bayram', uz: 'bayram' },
	{ id: 34, tr: 'bebek', uz: 'chaqaloq' },
	{ id: 35, tr: 'bey', uz: 'janob' },
	{ id: 36, tr: 'beyaz', uz: 'oq' },
	{ id: 37, tr: 'bilet', uz: 'bilet, chipta' },
	{ id: 38, tr: 'bilgisayar', uz: 'kompyuter' },
	{ id: 39, tr: 'bulaşık', uz: 'kir (idishlarga nisbatan)' },
	{ id: 40, tr: 'büro', uz: 'idora, byuro' },
	{ id: 41, tr: 'büyük', uz: 'katta, buyuk' },
	{ id: 42, tr: 'cami', uz: 'masjid, jome’' },
	{ id: 43, tr: 'cetvel', uz: 'lineyka, chizg‘ich' },
	{ id: 44, tr: 'cevap', uz: 'javob' },
	{ id: 45, tr: 'ceviz', uz: 'yong‘oq' },
	{ id: 46, tr: 'cuma', uz: 'juma' },
	{ id: 47, tr: 'cumartesi', uz: 'shanba' },
	{ id: 48, tr: 'çalışma odası', uz: 'ish xonasi' },
	{ id: 49, tr: 'çamaşır', uz: 'kir (material, kiyimlarga nisbatan)' },
	{ id: 50, tr: 'çamaşır odası', uz: 'kirxona' },
	{ id: 51, tr: 'çanta', uz: 'sumka' },
	{ id: 52, tr: 'çarşanba', uz: 'chorshanba' },
	{ id: 53, tr: 'çarşı', uz: 'bozor' },
	{ id: 54, tr: 'çay', uz: 'choy' },
	{ id: 55, tr: 'çiçek', uz: 'gul' },
	{ id: 56, tr: 'Çin', uz: 'Xitoy' },
	{ id: 57, tr: 'Çinli', uz: 'xıtoylik' },
	{ id: 58, tr: 'çocuk', uz: 'bola' },
	{ id: 59, tr: 'çocuk Odası', uz: 'bolalar xonasi' },
	{ id: 60, tr: 'çok', uz: 'ko‘p, juda' },
	{ id: 61, tr: 'defter', uz: 'daftar' },
	{ id: 62, tr: 'deniz', uz: 'dengiz' },
	{ id: 63, tr: 'ders', uz: 'dars' },
	{ id: 64, tr: 'doğum günü', uz: 'tug‘ilgan kun' },
	{ id: 65, tr: 'doktor', uz: 'shifokor' },
	{ id: 66, tr: 'dolap', uz: 'shkaf' },
	{ id: 67, tr: 'düğün', uz: 'to‘y' },
	{ id: 68, tr: 'eczane', uz: 'dorixona, apteka' },
	{ id: 69, tr: 'ekim', uz: 'oktyabr' },
	{ id: 70, tr: 'ekmek', uz: 'non' },
	{ id: 71, tr: 'elbise', uz: 'ko‘ylak (ayollarniki)' },
	{ id: 72, tr: 'elma', uz: 'olma' },
	{ id: 73, tr: 'erkek', uz: 'erkak' },
	{ id: 74, tr: 'ev', uz: 'uy' },
	{ id: 75, tr: 'eylül', uz: 'sentyabr' },
	{ id: 76, tr: 'fare', uz: 'sichqon' },
	{ id: 77, tr: 'fındık', uz: 'yong‘oq (funduk)' },
	{ id: 78, tr: 'fırça', uz: 'cho‘tka' },
	{ id: 79, tr: 'film', uz: 'film, kino' },
	{ id: 80, tr: 'fincan', uz: 'chashka' },
	{ id: 81, tr: 'Fransa', uz: 'Fransiya' },
	{ id: 82, tr: 'futbolcu', uz: 'futbolchi' },
	{ id: 83, tr: 'garaj', uz: 'garaj' },
	{ id: 84, tr: 'garson', uz: 'ofitsiant' },
	{ id: 85, tr: 'göz', uz: 'ko‘z' },
	{ id: 86, tr: 'Gri', uz: 'kulrang' },
	{ id: 87, tr: 'gül', uz: 'atirgul' },
	{ id: 88, tr: 'Güney Amerika', uz: 'Janubiy Amerika' },
	{ id: 89, tr: 'güzel', uz: 'chiroyli, go‘zal' },
	{ id: 90, tr: 'hâl', uz: 'hol, ahvol' },
	{ id: 91, tr: 'halı', uz: 'gilam' },
	{ id: 92, tr: 'hanım', uz: 'xonim' },
	{ id: 93, tr: 'hastalık', uz: 'kasallik' },
	{ id: 94, tr: 'havuç', uz: 'sabzi' },
	{ id: 95, tr: 'hayal', uz: 'orzu, hayol' },
	{ id: 96, tr: 'haziran', uz: 'iyun' },
	{ id: 97, tr: 'hemşire', uz: 'hamshira' },
	{ id: 98, tr: 'hiç', uz: 'hech' },
	{ id: 99, tr: 'ıspanak', uz: 'ismaloq' },
	{
		id: 100,
		tr: 'ızgara',
		uz: 'panjara (barbekyu pishiriladigan metalldan yasaladi)',
	},
	{ id: 101, tr: 'ideal', uz: 'ideal' },
	{ id: 102, tr: 'ilkbahar', uz: 'bahor' },
	{ id: 103, tr: 'inek', uz: 'sigir' },
	{ id: 104, tr: 'İngiliz', uz: 'ingliz' },
	{ id: 105, tr: 'İngiltere', uz: 'Angliya' },
	{ id: 106, tr: 'insan', uz: 'inson, odam' },
	{ id: 107, tr: 'İran', uz: 'Eron' },
	{ id: 108, tr: 'İranlı', uz: 'eronlik' },
	{ id: 109, tr: 'İspanya', uz: 'Ispaniya' },
	{ id: 110, tr: 'İspanyol', uz: 'ispan' },
	{ id: 111, tr: 'iş', uz: 'ish' },
	{ id: 112, tr: 'İtalya', uz: 'Italiya' },
	{ id: 113, tr: 'Japonya', uz: 'Yaponiya' },
	{ id: 114, tr: 'jeton', uz: 'jeton' },
	{ id: 115, tr: 'jilet', uz: 'jilet (ustara tig‘i)' },
	{ id: 116, tr: 'kadın', uz: 'ayol' },
	{ id: 117, tr: 'kafe', uz: 'kafe' },
	{ id: 118, tr: 'kahve', uz: 'qahva' },
	{ id: 119, tr: 'kahverengi', uz: 'malla' },
	{ id: 120, tr: 'kalabalık', uz: 'gavjum, tirband' },
	{ id: 121, tr: 'kalem', uz: 'qalam' },
	{ id: 122, tr: 'kalp', uz: 'qalb, yurak' },
	{ id: 123, tr: 'kapı', uz: 'eshik' },
	{ id: 124, tr: 'kasım', uz: 'noyabr' },
	{ id: 125, tr: 'kedi', uz: 'mushuk' },
	{ id: 126, tr: 'kırmızı', uz: 'qizil' },
	{ id: 127, tr: 'kış', uz: 'qısh' },
	{ id: 128, tr: 'kız', uz: 'qiz' },
	{ id: 129, tr: 'kira', uz: 'ijara' },
	{ id: 130, tr: 'kişi', uz: 'kishi' },
	{ id: 131, tr: 'kitap', uz: 'kitob' },
	{ id: 132, tr: 'koltuk', uz: 'o‘rindiq' },
	{ id: 133, tr: 'Kore', uz: 'Koreya' },
	{ id: 134, tr: 'Koreli', uz: 'koreys (koreyalik)' },
	{ id: 135, tr: 'köpek', uz: 'kuchuk, it' },
	{ id: 136, tr: 'köy', uz: 'qishloq' },
	{ id: 137, tr: 'kulaklık', uz: 'quloqchin (naushnik)' },
	{ id: 138, tr: 'kuş', uz: 'qush' },
	{ id: 139, tr: 'kutu', uz: 'quti (korobka)' },
	{ id: 140, tr: 'Kuzey Amerika', uz: 'Shimoliy Amerika' },
	{ id: 141, tr: 'kütüphane', uz: 'kutubxona' },
	{ id: 142, tr: 'lacivert', uz: 'lojuvard rang (бирюзовый)' },
	{ id: 143, tr: 'lale', uz: 'lola' },
	{ id: 144, tr: 'limon', uz: 'limon' },
	{ id: 145, tr: 'lokanta', uz: 'restoran' },
	{ id: 146, tr: 'lütfen', uz: 'iltimos, marhamat' },
	{ id: 147, tr: 'mağaza', uz: 'magazin' },
	{ id: 148, tr: 'makas', uz: 'qaychi' },
	{ id: 149, tr: 'Malezya', uz: 'Malayziya' },
	{ id: 150, tr: 'Malezyalı', uz: 'malayziyalik' },
	{ id: 151, tr: 'mart', uz: 'mart (oy)' },
	{ id: 152, tr: 'masa', uz: 'stol' },
	{ id: 153, tr: 'mavi', uz: 'moviy (rang)' },
	{ id: 154, tr: 'mayıs', uz: 'may (oy)' },
	{ id: 155, tr: 'merdiven', uz: 'zina' },
	{ id: 156, tr: 'meşgul', uz: 'band' },
	{ id: 157, tr: 'metro', uz: 'metro' },
	{ id: 158, tr: 'Mısır', uz: 'Misr' },
	{ id: 159, tr: 'Mısırlı', uz: 'misrlik' },
	{ id: 160, tr: 'millet', uz: 'millat' },
	{ id: 161, tr: 'misal', uz: 'misol' },
	{ id: 162, tr: 'mor', uz: 'siyohrang' },
	{ id: 163, tr: 'mutfak', uz: 'oshxona' },
	{ id: 164, tr: 'mühendis', uz: 'muhandis (injener)' },
	{ id: 165, tr: 'nar', uz: 'anor' },
	{ id: 166, tr: 'Nijerya', uz: 'Nigeriya' },
	{ id: 167, tr: 'nisan', uz: 'aprel (oy)' },
	{ id: 168, tr: 'numara', uz: 'raqam (nomer)' },
	{ id: 169, tr: 'ocak', uz: 'yanvar (oy)' },
	{ id: 170, tr: 'oda', uz: 'xona' },
	{ id: 171, tr: 'orman', uz: 'o‘rmon' },
	{ id: 172, tr: 'otel', uz: 'mehmonx' },
  { id: 173, tr: 'otobüs', uz: 'avtobus' },
  { id: 174, tr: 'öğrenci', uz: 'o‘quvchi' },
  { id: 175, tr: 'öğretmen', uz: 'o‘qituvchi' },
  { id: 176, tr: 'ördek', uz: 'o‘rdak' },
  { id: 177, tr: 'paket', uz: 'paket' },
  { id: 178, tr: 'Pakistan', uz: 'Pokiston' },
  { id: 179, tr: 'Pakistanlı', uz: 'pokistonlik' },
  { id: 180, tr: 'park', uz: 'istirohat bog‘i (park)' },
  { id: 181, tr: 'patates', uz: 'kartoshka' },
  { id: 182, tr: 'pazar', uz: 'yakshanba' },
  { id: 183, tr: 'para', uz: 'pul' },
  { id: 184, tr: 'paradösü', uz: 'palto' },
  { id: 185, tr: 'pazartesi', uz: 'dushanba' },
  { id: 186, tr: 'pembe', uz: 'pushti (rang)' },
  { id: 187, tr: 'pencere', uz: 'deraza' },
  { id: 188, tr: 'perşembe', uz: 'payshanba' },
  { id: 189, tr: 'petrol', uz: 'benzin' },
  { id: 190, tr: 'piyano', uz: 'piyanino' },
  { id: 191, tr: 'polis', uz: 'militsiya' },
  { id: 192, tr: 'portakal', uz: 'apelsin' },
  { id: 193, tr: 'postacı', uz: 'pochtachi' },
  { id: 194, tr: 'profesör', uz: 'professor' },
  { id: 195, tr: 'radyo', uz: 'radio' },
  { id: 196, tr: 'resim', uz: 'rasm' },
  { id: 197, tr: 'rol', uz: 'rol' },
  { id: 198, tr: 'roman', uz: 'roman' },
  { id: 199, tr: 'Rus', uz: 'rus' },
  { id: 200, tr: 'Rusya', uz: 'Rossiya' },
  { id: 201, tr: 'saat', uz: 'soat' },
  { id: 202, tr: 'sabah', uz: 'tong' },
  { id: 203, tr: 'saç', uz: 'soch' },
  { id: 204, tr: 'salı', uz: 'seshanba' },
  { id: 205, tr: 'salon', uz: 'mehmonxona, zal' },
  { id: 206, tr: 'sandalye', uz: 'stul' },
  { id: 207, tr: 'sarı', uz: 'sariq' },
  { id: 208, tr: 'sembol', uz: 'simvol' },
  { id: 209, tr: 'seyahat', uz: 'sayohat' },
  { id: 210, tr: 'sıra', uz: 'navbat, parta' },
  { id: 211, tr: 'silgi', uz: 'o‘chirg‘ich' },
  { id: 212, tr: 'siyah', uz: 'qora' },
  { id: 213, tr: 'sokak', uz: 'ko‘cha' },
  { id: 214, tr: 'Somali', uz: 'Somali' },
  { id: 215, tr: 'sonbahar', uz: 'kuz' },
  { id: 216, tr: 'soru', uz: 'savol' },
  { id: 217, tr: 'sorun', uz: 'muammo' },
  { id: 218, tr: 'sözlük', uz: 'lug‘at' },
  { id: 219, tr: 'Suriye', uz: 'Suriya' },
  { id: 220, tr: 'şarkıcı', uz: 'qo‘shiqchi, ashulachi' },
  { id: 221, tr: 'şemsiye', uz: 'soyabon' },
  { id: 222, tr: 'şişe', uz: 'shisha' },
  { id: 223, tr: 'şubat', uz: 'fevral (oy)' },
  { id: 224, tr: 'tahta', uz: 'taxta (doska)' },
  { id: 225, tr: 'tavuk', uz: 'tovuq' },
  { id: 226, tr: 'telefon', uz: 'telefon' },
  { id: 227, tr: 'temiz', uz: 'toza' },
  { id: 228, tr: 'temmuz', uz: 'iyul (oy)' },
  { id: 229, tr: 'top', uz: 'koptok (to‘p)' },
  { id: 230, tr: 'turist', uz: 'turist, sayyoh' },
  { id: 231, tr: 'turuncu', uz: 'sabzirang' },
  { id: 232, tr: 'Türk', uz: 'turk' },
  { id: 233, tr: 'Türkiye', uz: 'Turkiya' },
  { id: 234, tr: 'uçak', uz: 'samolyot' },
  { id: 235, tr: 'uçurtma', uz: 'varrak' },
  { id: 236, tr: 'üzüm', uz: 'uzum' },
  { id: 237, tr: 'vagon', uz: 'vagon' },
  { id: 238, tr: 'yabancı', uz: 'chet ellik, begona' },
  { id: 239, tr: 'yatak odası', uz: 'yotoqxona' },
  { id: 240, tr: 'yaz', uz: 'yoz' },
  { id: 241, tr: 'yemek', uz: 'ovqat' },
  { id: 242, tr: 'yeni', uz: 'yangi' },
  { id: 243, tr: 'yeşil', uz: 'yashil' },
  { id: 244, tr: 'yıl', uz: 'yil' },
  { id: 245, tr: 'yıldız', uz: 'yulduz' },
  { id: 246, tr: 'Yunan', uz: 'yunon' },
  { id: 247, tr: 'Yunanistan', uz: 'Yunoniston' },
  { id: 248, tr: 'yüzük', uz: 'uzuk' },
  { id: 249, tr: 'zeytin', uz: 'zaytun' },
  { id: 250, tr: 'zürafa', uz: 'jirafa' },
  { id: 251, tr: 'açmak', uz: 'ochmoq' },
  { id: 252, tr: 'bakmak', uz: 'boqmoq, qaramoq' },
  { id: 253, tr: 'cevap vermek', uz: 'javob bermoq' },
  { id: 254, tr: 'dinlemek', uz: 'tinglamoq' },
  { id: 255, tr: 'etmek', uz: 'etmoq, qilmoq' },
  { id: 256, tr: 'gelmek', uz: 'kelmoq' },
  { id: 257, tr: 'görüşmek', uz: 'ko‘rishmoq' },
  { id: 258, tr: 'kapatmak', uz: 'yopmoq' },
  { id: 259, tr: 'okumak', uz: 'o‘qimoq' },
  { id: 260, tr: 'olmak', uz: 'bo‘lmoq' },
  { id: 261, tr: 'tamamlamak', uz: 'tamomlamoq, tugatmoq' },
  { id: 262, tr: 'tekrar etmek', uz: 'takrorlamoq' },
  { id: 263, tr: 'yazmak', uz: 'yozmoq' },
  { id: 264, tr: 'Affedersiniz', uz: 'kechirasiz' },
  { id: 265, tr: 'Afiyet olsun', uz: 'yoqimli ishtaha' },
  { id: 266, tr: 'Bol şanslar', uz: 'omad yor bo‘lsin' },
  { id: 267, tr: 'Çok yaşa', uz: 'ko‘p yasha (sog‘ bo‘l – aksa urgan insonga nisbatan)' },
  { id: 268, tr: 'Geçmiş olsun', uz: 'ortda qolgani rost bo‘lsin' },
  { id: 269, tr: 'Görüşürüz / Görüşmek üzere', uz: 'ko‘rishamiz, ko‘rishguncha' },
  { id: 270, tr: 'Güle güle', uz: 'xayr' },
  { id: 271, tr: 'Günaydın', uz: 'xayrli tong' },
  { id: 272, tr: 'Hoş bulduk', uz: 'xush ko‘rdik' },
  { id: 273, tr: 'Hoş geldin', uz: 'xush kelding' },
  { id: 274, tr: 'Hoşça kal', uz: 'yaxshi qol' },
  { id: 275, tr: 'Lütfen', uz: 'iltimos, marhamat' },
  { id: 276, tr: 'Merhaba', uz: 'salom' },
  { id: 277, tr: 'Özür dilerim', uz: 'uzr so‘rayman' },
  { id: 278, tr: 'Rica ederim', uz: 'arzimaydi, iltimos qilaman' },
  { id: 279, tr: 'Tamam', uz: 'hop, mayli (ok)' },
  { id: 280, tr: 'Tebrikler', uz: 'tabriklar, tabriklayman' },
  { id: 281, tr: 'Üzgünüm', uz: 'afsusdaman' }
];

export const wordsUnit2 = [
  { id: 1, tr: 'aç', uz: 'och' },
  { id: 2, tr: 'açık', uz: 'ochiq' },
  { id: 3, tr: 'adres', uz: 'manzil (adres)' },
  { id: 4, tr: 'akşam', uz: 'kechqurun, oqshom' },
  { id: 5, tr: 'alışveriş', uz: 'savdo-sotiq' },
  { id: 6, tr: 'alışveriş merkezi', uz: 'savdo-sotiq markazi' },
  { id: 7, tr: 'alt', uz: 'ost, pastroq' },
  { id: 8, tr: 'anahtar', uz: 'kalit' },
  { id: 9, tr: 'artı', uz: 'qo‘shuv +' },
  { id: 10, tr: 'aşcı', uz: 'oshpaz' },
  { id: 11, tr: 'avukat', uz: 'advokat' },
  { id: 12, tr: 'ay', uz: 'oy' },
  { id: 13, tr: 'banka', uz: 'bank' },
  { id: 14, tr: 'başarılı', uz: 'muvaffaqiyatli' },
  { id: 15, tr: 'bekâr', uz: 'turmush qurmagan, bo‘ydoq yoki ajrashgan' },
  { id: 16, tr: 'bilet', uz: 'bilet, chipta' },
  { id: 17, tr: 'bina', uz: 'bino' },
  { id: 18, tr: 'birçok', uz: 'bir qancha' },
  { id: 19, tr: 'boş', uz: 'bo‘sh' },
  { id: 20, tr: 'bozuk', uz: 'buzuq' },
  { id: 21, tr: 'bölüm', uz: 'bo‘lim' },
  { id: 22, tr: 'bölü', uz: 'bo’lish' },
  { id: 23, tr: 'bugün', uz: 'bugun' },
  { id: 24, tr: 'burada', uz: 'bu yerda' },
  { id: 25, tr: 'bütün', uz: 'butun' },
  { id: 26, tr: 'büyük', uz: 'katta' },
  { id: 27, tr: 'cesur', uz: 'jasur' },
  { id: 28, tr: 'ciddi', uz: 'jiddiy' },
  { id: 29, tr: 'çalışkan', uz: 'mehnatkash' },
  { id: 30, tr: 'çarpı', uz: 'ko‘paytiruv *' },
  { id: 31, tr: 'çirkin', uz: 'xunuk' },
  { id: 32, tr: 'çöp kutusu', uz: 'chiqindi qutisi' },
  { id: 33, tr: 'çünkü', uz: 'chunki' },
  { id: 34, tr: 'dağınık', uz: 'tartibsiz' },
  { id: 35, tr: 'dar', uz: 'tor' },
  { id: 36, tr: 'dergi', uz: 'jurnal' },
  { id: 37, tr: 'dikkatli', uz: 'e’tiborli, diqqatli' },
  { id: 38, tr: 'dikkatsiz', uz: 'e’tiborsiz, diqqatsiz' },
  { id: 39, tr: 'doğru', uz: 'to‘g‘ri' },
  { id: 40, tr: 'doğum tarihi', uz: 'tug‘ilgan sana, oy, yil' },
  { id: 41, tr: 'doktor', uz: 'shifikor (doktor)' },
  { id: 42, tr: 'dolu', uz: 'to‘la' },
  { id: 43, tr: 'domates', uz: 'pomidor' },
  { id: 44, tr: 'dosya', uz: 'fayl, papka' },
  { id: 45, tr: 'durak', uz: 'bekat (ostanovka)' },
  { id: 46, tr: 'duvar', uz: 'devor' },
  { id: 47, tr: 'düzenli', uz: 'tartibli, muntazam' },
  { id: 48, tr: 'eczacı', uz: 'dorixonachi' },
  { id: 49, tr: 'eğlenceli', uz: 'ko‘ngilochar, qiziqarli, hushchaqchaq' },
  { id: 50, tr: 'eksi', uz: 'ayiruv' },
  { id: 51, tr: 'eski', uz: 'eski' },
  { id: 52, tr: 'eşya', uz: 'ashyo, narsa' },
  { id: 53, tr: 'evli', uz: 'oilali' },
  { id: 54, tr: 'fakir', uz: 'kambag‘al' },
  { id: 55, tr: 'fark', uz: 'farq' },
  { id: 56, tr: 'fırın', uz: 'pech, non sotadigan do‘kon' },
  { id: 57, tr: 'form', uz: 'shakl' },
  { id: 58, tr: 'gazete', uz: 'gazeta' },
  { id: 59, tr: 'genellikle', uz: 'odatda' },
  { id: 60, tr: 'genç', uz: 'yosh (odam)' },
  { id: 61, tr: 'geniş', uz: 'keng' },
  { id: 62, tr: 'güçlü', uz: 'kuchli' },
  { id: 63, tr: 'güçsüz', uz: 'kuchsiz' },
  { id: 64, tr: 'gün', uz: 'kun' },
  { id: 65, tr: 'gündüz', uz: 'kunduz' },
  { id: 66, tr: 'güvenli', uz: 'ishonchli, xatarsiz' },
  { id: 67, tr: 'hafta sonu', uz: 'hafta oxiri' },
  { id: 68, tr: 'hasta', uz: 'kasal' },
  { id: 69, tr: 'hastane', uz: 'kasalxona' },
  { id: 70, tr: 'hemşire', uz: 'hamshira' },
  { id: 71, tr: 'her zaman', uz: 'har doim' },
  { id: 72, tr: 'hızlı', uz: 'tez' },
  { id: 73, tr: 'hostes', uz: 'styuardessa' },
  { id: 74, tr: 'içecek', uz: 'ichimlik' },
  { id: 75, tr: 'istasyon', uz: 'stansiya' },
  { id: 76, tr: 'itfaiyeci', uz: 'o‘t o‘chiruvchi' },
  { id: 77, tr: 'kaç', uz: 'nechta, qancha' },
  { id: 78, tr: 'kaçıncı', uz: 'nechanchi' },
  { id: 79, tr: 'kat', uz: 'qavat' },
  { id: 80, tr: 'kırmızı', uz: 'qizil' },
  { id: 81, tr: 'kantin', uz: 'oshxona (maktabda)' },
  { id: 82, tr: 'kapalı', uz: 'yopiq' },
  { id: 83, tr: 'kardeş', uz: 'qarindosh, jigar' },
  { id: 84, tr: 'kasap', uz: 'qassob' },
  { id: 85, tr: 'kasiyer', uz: 'kassir, hisobchi' },
  { id: 86, tr: 'kırmızı', uz: 'qizil' },
  { id: 87, tr: 'kısa', uz: 'qisqa' },
  { id: 88, tr: 'kıskanç', uz: 'rashkchi, qizg‘anchiq' },
  { id: 89, tr: 'kibar', uz: 'xushmuomala' },
  { id: 90, tr: 'kilo', uz: 'kilogramm' },
  { id: 91, tr: 'kirli', uz: 'kir' },
  { id: 92, tr: 'kitaplık', uz: 'kitob javoni' },
  { id: 93, tr: 'kolay', uz: 'oson' },
  { id: 94, tr: 'komik', uz: 'kulguli, hazilkash' },
  { id: 95, tr: 'konuşkan', uz: 'ko‘p gapiruvchi, suhbatga kirishimli' },
  { id: 96, tr: 'koridor', uz: 'yo‘lak, koridor' },
  { id: 97, tr: 'kötü', uz: 'yomon' },
  { id: 98, tr: 'kuaför', uz: 'sartarosh (ayollar)' },
  { id: 99, tr: 'kuyumcu', uz: 'zargar' },
  { id: 100, tr: 'küçük', uz: 'kichkina' },
  { id: 101, tr: 'lamba', uz: 'lampa' },
  { id: 102, tr: 'lig', uz: 'liga (sportda)' },
  { id: 103, tr: 'liste', uz: 'ro‘yxat' },
  { id: 104, tr: 'mahalle', uz: 'mahalla' },
  { id: 105, tr: 'manav', uz: 'sabzavot do‘koni' },
  { id: 106, tr: 'market', uz: 'market, do‘kon' },
  { id: 107, tr: 'mutfak', uz: 'oshxona (uydagi)' },
  { id: 108, tr: 'mutlu', uz: 'baxtli, xursand' },
  { id: 109, tr: 'mutsuz', uz: 'baxtsiz' },
  { id: 110, tr: 'nerede', uz: 'qayerda' },
  { id: 111, tr: 'nesne', uz: 'ob‘ekt' },
  { id: 112, tr: 'niçin', uz: 'nima uchun' },
  { id: 113, tr: 'ocak', uz: 'yanvar' },
  { id: 114, tr: 'ofis', uz: 'ofis' },
  { id: 115, tr: 'olimpiyat', uz: 'olimpiada' },
  { id: 116, tr: 'orada', uz: 'u yerda' },
  { id: 117, tr: 'öğleden sonra', uz: 'tushdan(obeddan) keyin' },
  { id: 118, tr: 'öğretmen', uz: 'o‘qituvchi' },
  { id: 119, tr: 'önemli', uz: 'muhim' },
  { id: 120, tr: 'önemsiz', uz: 'nomuhim' },
  { id: 121, tr: 'pahalı', uz: 'qimmat' },
  { id: 122, tr: 'pastane', uz: 'qandolatxona' },
  { id: 123, tr: 'pembe', uz: 'pushti' },
  { id: 124, tr: 'polis', uz: 'militsiya' },
  { id: 125, tr: 'postane', uz: 'pochtaxona' },
  { id: 126, tr: 'projektör', uz: 'proyektor' },
  { id: 127, tr: 'psikolog', uz: 'pasixolog' },
  { id: 128, tr: 'sayı', uz: 'son' },
  { id: 129, tr: 'sabah', uz: 'ertalab, tong' },
  { id: 130, tr: 'sağlam', uz: 'soz, sog‘lom' },
  { id: 131, tr: 'sehpa', uz: 'gazeta stoli (qahva stoli)' },
  { id: 132, tr: 'sekreter', uz: 'sekretar' },
  { id: 133, tr: 'semt', uz: 'guzar, massiv' },
  { id: 134, tr: 'sessiz', uz: 'sokin, kamgap' },
  { id: 135, tr: 'sıcak', uz: 'issiq' },
  { id: 136, tr: 'sıfat', uz: 'sifat' },
  { id: 137, tr: 'sinirli', uz: 'asabiy, jahldor' },
  { id: 138, tr: 'soğuk', uz: 'sovuq' },
  { id: 139, tr: 'sokak', uz: 'ko‘cha' },
  { id: 140, tr: 'sosyal', uz: 'sotsial, ijtimoiy kirishimli' },
  { id: 141, tr: 'şehir', uz: 'shahar' },
  { id: 142, tr: 'şimdi', uz: 'hozir' },
  { id: 143, tr: 'şimdilik', uz: 'hozircha' },
  { id: 144, tr: 'şişman', uz: 'semiz' },
  { id: 145, tr: 'tabak', uz: 'idish-tovoq' },
  { id: 146, tr: 'tamirci', uz: 'ta‘mirlovchi' },
  { id: 147, tr: 'tarih', uz: 'tarix, sana' },
  { id: 148, tr: 'tatil', uz: 'ta’til, bayram (kanikul)' },
  { id: 149, tr: 'tehlikeli', uz: 'tahlikali, xatarli' },
  { id: 150, tr: 'tembel', uz: 'yalqov, ishyoqmas, tambal' },
  { id: 151, tr: 'temiz', uz: 'toza' },
  { id: 152, tr: 'temizlik görevlisi', uz: 'farrosh, tozalik xodimi' },
  { id: 153, tr: 'tezgahtar', uz: 'sotuvchi' },
  { id: 154, tr: 'tuzlu', uz: 'tuzli, sho‘r' },
  { id: 155, tr: 'ucuz', uz: 'arzon' },
  { id: 156, tr: 'uzak', uz: 'uzoq' },
  { id: 157, tr: 'uzun', uz: 'uzun' },
  { id: 158, tr: 'üst', uz: 'ust, tepa' },
  { id: 159, tr: 'var', uz: 'bor' },
  { id: 160, tr: 'veteriner', uz: 'veterinar' },
  { id: 161, tr: 'yakın', uz: 'yaqin' },
  { id: 162, tr: 'yanlış', uz: 'xato, yanglish' },
  { id: 163, tr: 'yarışma', uz: 'musobaqa' },
  { id: 164, tr: 'yastık', uz: 'yostiq' },
  { id: 165, tr: 'yaş', uz: 'yosh' },
  { id: 166, tr: 'yaşlı', uz: 'yoshi katta, qari' },
  { id: 167, tr: 'yavaş', uz: 'sekin, bosiq' },
  { id: 168, tr: 'yazı tahtası', uz: 'doska, yozuv taxtasi' },
  { id: 169, tr: 'yeni', uz: 'yangi' },
  { id: 170, tr: 'yer', uz: 'joy' },
  { id: 171, tr: 'yıl', uz: 'yil' },
  { id: 172, tr: 'yiyecek', uz: 'yegulik' },
  { id: 173, tr: 'yoğun', uz: 'band' },
  { id: 174, tr: 'yok', uz: 'yo‘q' },
  { id: 175, tr: 'yorgun', uz: 'horg‘in, charchagan' },
  { id: 176, tr: 'yorucu', uz: 'charchatuvchi' },
  { id: 177, tr: 'yumuşak', uz: 'yumshoq' },
  { id: 178, tr: 'zamir', uz: 'olmosh (so‘z turkumi)' },
  { id: 179, tr: 'zayıf', uz: 'ozg‘in' },
  { id: 180, tr: 'zengin', uz: 'boy' },
  { id: 181, tr: 'zor', uz: 'qiyin' },
  { id: 182, tr: 'aramak', uz: 'qidirmoq, qo‘ng‘iroq qilmoq' }
];